### ISSUE TITLE
No exception fired on video data loading error

### ISSUE THREAD

**Issue by krida2000** [zezo357/flutter_meedu_videoplayer#102]
If video loaded from invalid url no exception is fired and `MeeduPlayerController.dataStatus` not changed to `error`.
How should I handle video loading errors? 

Code sample:
``` dart

await _meeduPlayerController.setDataSource(
        DataSource(
          type: DataSourceType.network,
          source: "https://some-invalid-url.com/video/123.mp4",
        ),
        autoplay: true,
        looping: false,
    );

```

**Comment by zezo357** [comment]
On desktop?

**Comment by zezo357** [comment]
Yes I am still trying to fix that since I couldn't get the error from media_kit

**Comment by zezo357** [comment]
Related issue.
https://github.com/alexmercerind/media_kit/issues/218

If I got time I may open a pr on media_kit for a fix for that problem

**Comment by zezo357** [comment]
fixed on `4.2.11-dev-3` please check and reopen it there is any other problem

**Comment by zezo357** [comment]
@krida2000  due to problems with my fix, i made the code only log errors, when media_kit provides a better solution i will integrate it, sorry for that

**Comment by zezo357** [comment]
should be fixed in this new release since media_kit added error stream
