### ISSUE TITLE
Video cannot be opened correctly on macos

### ISSUE THREAD

**Issue by aohanhe** [zezo357/flutter_meedu_videoplayer#103]
In our tests, we found that the loading video under macos is always in a waiting state, is this a bug?Or am I missing some key configuration？
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/23033236/ac18eba0-5608-421c-9c8f-0184605621d1)

**Comment by zezo357** [comment]
Can you provide a sample code to test with?


But no it should be working correctly



I will try to expose the logs of media_kit in next release since it's important to be able to see what is happening

**Comment by zezo357** [comment]
You need to add: for internet access on macos

<key>com.apple.security.network.client</key>
<true/>
to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements.

**Comment by zezo357** [comment]
fixed on `4.2.11-dev-3` please check and reopen it there is any other problem
