### ISSUE TITLE
[Windows] Failed to create EGL surface.

### ISSUE THREAD

**Issue by coder-xb** [zezo357/flutter_meedu_videoplayer#106]
Hello, I am currently using this plugin ``flutter_meedu_videoplayer: ^4.2.10`` to develop video playback functionality on Windows systems, but I have encountered the following issue:
![WX20230602-152619@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/f73f9f66-90c3-48ca-a37f-36182f01b1fb)
The effect it presents is as follows, unable to play or perform any operations:
![WX20230602-154634@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/20248c5e-1e97-4ffc-9d6d-a1cb8f39a301)
Here are the results of ``flutter doctor -v``:
![WX20230602-152054@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/6fae5129-9090-47d9-b395-b39ca7810281)
I need some help, thanks!

**Comment by zezo357** [comment]
was it working before? if yes i may have a fix for it

**Comment by zezo357** [comment]
can you run `flutter pub upgrade` and test again, i made the code only log errors without throwing exceptions since that was a false positive

**Comment by coder-xb** [comment]
> can you run `flutter pub upgrade` and test again, i made the code only log errors without throwing exceptions since that was a false positive

Thank, I ran 'Flutter pub upload' and test again, but the issue still exists.I have used it on IOS before and everything is normal

**Comment by coder-xb** [comment]
> was it working before? if yes i may have a fix for it

This is the first time it working on Windows

**Comment by zezo357** [comment]
> > was it working before? if yes i may have a fix for it
> 
> This is the first time it working on Windows

ok flutter pub upgrade and let me know what happened

**Comment by zezo357** [comment]
> > can you run `flutter pub upgrade` and test again, i made the code only log errors without throwing exceptions since that was a false positive
> 
> Thank, I ran 'Flutter pub upgrade' and test again, but the issue still exists.I have used it on IOS before and everything is normal
sorry i deleted you comment by mistake 
so its not working ? fully? no output ? and what is the logs for it?

**Comment by coder-xb** [comment]
> sorry i deleted you comment by mistake so its not working ? fully? no output ? and what is the logs for it?

yes，it is not working，the logs for it is the first screenshot in this issue，that is all

**Comment by zezo357** [comment]
from what i know media_kit uses hardware rendering and if failed they fallback to software one 

so this weird, you are using a windows vm on macbook right? i think something is which causes this problem

**Comment by coder-xb** [comment]
> from what i know media_kit uses hardware rendering and if failed they fallback to software one
> 
> so this weird, you are using a windows vm on macbook right? i think something is missing for windows setup which causes this problem

Yes, I am running a Windows virtual machine on macOS，maybe causes this problem

**Comment by coder-xb** [comment]
> > from what i know media_kit uses hardware rendering and if failed they fallback to software one
> > so this weird, you are using a windows vm on macbook right? i think something is missing for windows setup which causes this problem

Yes, I am running a Windows virtual machine on macOS，maybe causes this problem
As you said, if it were on real Windows, wouldn't this problem? I'll give it a try

**Comment by zezo357** [comment]
> > from what i know media_kit uses hardware rendering and if failed they fallback to software one
> > so this weird, you are using a windows vm on macbook right? i think something is missing for windows setup which causes this problem
> 
> Yes, I am running a Windows virtual machine on macOS，maybe causes this problem

can you let me know did you setup it?

i can test it and maybe find a fix for it



>  As you said, if it were on real Windows, wouldn't this problem? I'll give it a try

yes on a normal windows device it works correctly 

Note: after flutter pub upgrade it should not throw an exception, it should only show those logs can you confirm that

**Comment by coder-xb** [comment]
> Note: after flutter pub upgrade it should not throw an exception, it should only show those logs can you confirm that

No，I didn't setup the windows vm，that is in the company's local area network

It's really strange that after running ``flutter pub upgrade``, it actually works:

D:\Source\flutter\bin\flutter.bat --no-color pub upgrade
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Resolving dependencies...
  args 2.4.1
  asn1lib 1.4.0
  async 2.11.0
  audioplayers 4.1.0
  audioplayers_android 3.0.2
  audioplayers_darwin 4.1.0
  audioplayers_linux 2.1.0
  audioplayers_platform_interface 5.0.1
  audioplayers_web 3.1.0
  audioplayers_windows 2.0.2
  auto_orientation 2.3.1
  boolean_selector 2.1.1
  characters 1.3.0
  clock 1.1.1
  collection 1.17.1 (1.17.2 available)
  connectivity_plus 4.0.1
  connectivity_plus_platform_interface 1.2.4
  convert 3.1.1
  crypto 3.0.3
  csslib 0.17.3
  cupertino_icons 1.0.5
  dbus 0.7.8
  decimal 2.3.2
  device_info_plus 9.0.2
  device_info_plus_platform_interface 7.0.0
  dio 5.1.2
  easy_refresh 3.3.2+1
  encrypt 5.0.1
  extended_image 8.0.2
  extended_image_library 3.5.1
  extended_text 11.0.0
  extended_text_field 12.0.0
  extended_text_library 11.0.1
  fake_async 1.3.1
  ffi 2.0.2
  file 6.1.4 (7.0.0 available)
  file_picker 5.3.1 (5.3.2 available)
  flutter 0.0.0 from sdk flutter
  flutter_highlight 0.7.0
  flutter_lints 2.0.1
  flutter_localizations 0.0.0 from sdk flutter
  flutter_meedu 8.3.1
  flutter_meedu_videoplayer 4.2.10
  flutter_plugin_android_lifecycle 2.0.15
  flutter_spinkit 5.2.0
  flutter_test 0.0.0 from sdk flutter
  flutter_web_plugins 0.0.0 from sdk flutter
  fullscreen_window 1.0.4
  get 4.6.5
  get_storage 2.1.1
  highlight 0.7.0
  hotkey_manager 0.1.7
  html 0.15.3
  http 0.13.6 (1.0.0 available)
  http_client_helper 2.0.4
  http_parser 4.0.2
  intl 0.18.0 (0.18.1 available)
  js 0.6.7
  lints 2.1.0
  local_notifier 0.1.5
  markdown 7.1.0
  markdown_widget 2.2.0
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  media_kit 0.0.9+1
  media_kit_libs_linux 1.0.2
  media_kit_libs_macos_video 1.0.5
  media_kit_libs_windows_video 1.0.2
  media_kit_native_event_loop 1.0.4
  media_kit_video 0.0.12
  meedu 8.0.2
  meta 1.9.1
  mime 1.0.4
  nm 0.5.0
  package_info_plus 4.0.2
  package_info_plus_platform_interface 2.0.1
  path 1.8.3
  path_drawing 1.0.1
  path_parsing 1.0.1
  path_provider 2.0.15
  path_provider_android 2.0.27
  path_provider_foundation 2.2.3
  path_provider_linux 2.1.11
  path_provider_platform_interface 2.0.6
  path_provider_windows 2.1.6
  permission_handler 10.2.0
  permission_handler_android 10.2.1
  permission_handler_apple 9.0.8
  permission_handler_platform_interface 3.9.0
  permission_handler_windows 0.1.2
  petitparser 5.4.0
  platform 3.1.0
  plugin_platform_interface 2.1.4
  pointycastle 3.7.3
  process 4.2.4
  qr 3.0.1
  qr_flutter 4.1.0
  rational 2.2.2
  safe_local_storage 1.0.2
  screen_brightness 0.2.2
  screen_brightness_android 0.1.0+2
  screen_brightness_ios 0.1.0
  screen_brightness_macos 0.1.0+1
  screen_brightness_platform_interface 0.1.0
  screen_brightness_windows 0.1.1
  screen_capturer 0.1.4
  screen_retriever 0.1.6
  scroll_to_index 3.0.1
  scrollable_positioned_list 0.3.8
  shared_preferences 2.1.1
  shared_preferences_android 2.1.4
  shared_preferences_foundation 2.2.2
  shared_preferences_linux 2.2.0
  shared_preferences_platform_interface 2.2.0
  shared_preferences_web 2.1.0
  shared_preferences_windows 2.2.0
  sky_engine 0.0.99 from sdk flutter
  source_span 1.9.1 (1.10.0 available)
  sqflite 2.2.8+4
  sqflite_common 2.4.5
  sqflite_common_ffi 2.2.5
  sqlite3 1.11.1
  stack_trace 1.11.0
  stream_channel 2.1.1
  stream_transform 2.1.0
  string_scanner 1.2.0
  synchronized 3.1.0
  term_glyph 1.2.1
  test_api 0.5.1 (0.6.0 available)
  typed_data 1.3.2
  universal_platform 1.0.0+1
  uri_parser 2.0.2
  url_launcher 6.1.11
  url_launcher_android 6.0.35
  url_launcher_ios 6.1.4
  url_launcher_linux 3.0.5
  url_launcher_macos 3.0.5
  url_launcher_platform_interface 2.1.2
  url_launcher_web 2.0.17
  url_launcher_windows 3.0.6
  uuid 3.0.7
  vector_math 2.1.4
  video_player 2.6.1
  video_player_android 2.4.8
  video_player_avfoundation 2.4.6
> video_player_media_kit 0.0.15 (was 0.0.13)
  video_player_platform_interface 6.1.0
  video_player_web 2.0.16
  visibility_detector 0.4.0+2
  volume_controller 2.0.7
  wakelock 0.6.2
  wakelock_macos 0.4.0
  wakelock_platform_interface 0.3.0
  wakelock_web 0.4.0
! wakelock_windows 0.2.2 from git https://github.com/timsneath/wakelock at 2a9bca in wakelock_windows (overridden)
  web_socket_channel 2.4.0
  win32 4.1.4 (5.0.3 available)
  win32_registry 1.1.0 (1.1.1 available)
  window_manager 0.3.4
  xdg_directories 1.0.0
  xml 6.3.0
Changed 1 dependency!
11 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Process finished with exit code 0

**Comment by zezo357** [comment]
> > Note: after flutter pub upgrade it should not throw an exception, it should only show those logs can you confirm that
> 
> No，I didn't setup the windows vm，that is in the company's local area network
> 
> It's really strange that after running `flutter pub upgrade`, it actually works:


running flutter pub upgrade made your app use latest package i have which is video_player_media_kit 0.0.15 in which i only show logs of errors and not throw them,

**Comment by zezo357** [comment]
since those errors are handled by media_kit when i throw the exception it didnt work

**Comment by zezo357** [comment]
so now everything works correctly and we can close the issue, right?

**Comment by coder-xb** [comment]
> > > Note: after flutter pub upgrade it should not throw an exception, it should only show those logs can you confirm that
> > 
> > 
> > No，I didn't setup the windows vm，that is in the company's local area network
> > It's really strange that after running `flutter pub upgrade`, it actually works:
> 
> running flutter pub upgrade made your app use latest package i have which is video_player_media_kit 0.0.15 in which i only show logs of errors and not throw them,

> so now everything works correctly and we can close the issue, right?

Okay, Thank you for your help. Now, everything is normal
