### ISSUE TITLE
Subtitle Size

### ISSUE THREAD

**Issue by CoocooFroggy** [zezo357/flutter_meedu_videoplayer#107]
Hello,

Is there a way to change the font size of the subtitles in the video? The text seems to be very small when the video is put in full-screen.

## Windowed
<img width="915" alt="windowed" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/45371102/374dbbd7-b62d-4814-8d27-877c57e0d07a">

## Full Screen
<img width="1440" alt="full-screen" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/45371102/da90f19a-00d1-469d-a2d2-42c9c0e8deed">

**Comment by zezo357** [comment]
You can change font size throughout the video player using the responsive class , check custom sizes in the examples

**Comment by CoocooFroggy** [comment]
Wow I appreciate the update so much!! I will try it out and let you know
