### ISSUE TITLE
Caching support (Question)

### ISSUE THREAD

**Issue by sommye-ctr** [zezo357/flutter_meedu_videoplayer#110]
Does the library support caching, i.e. caching video in device's local storage so that it is retained between app sessions?

**Comment by zezo357** [comment]
no its on memory for both media_kit and video_player

**Comment by sommye-ctr** [comment]
Oh okay thanks for the reply. Also I'm not sure if this question should be asked here or on media kit library but does the player pick up on embedded subtitles. For eg in mkv container, subtitle files are embedded, so are they recognised by the player?

**Comment by zezo357** [comment]
You can try it by setting media_kit to true , for Android and iOS , and test 

I am not sure if it does

**Comment by sommye-ctr** [comment]
Okay thanks. 

I was just testing the player and was wondering how to add multiple subtitles to a data source. For example, I have https url for the subtitle (srt) file, how do I add all of them?
