### ISSUE TITLE
multi subtitle support

### ISSUE THREAD

**Issue by micodev** [zezo357/flutter_meedu_videoplayer#111]
is there any implementation that I can use to get multi subtitle and choose one of them and it will change the subtitle without re initiate the DataSource ?

**Comment by zezo357** [comment]
> is there any implementation that I can use to get multi subtitle and choose one of them and it will change the subtitle without re initiate the DataSource ?
> 

Right now, it's not 


I will try to implement it in the next release and let you know (no promises)

**Comment by micodev** [comment]
````
  await meeduPlayerController.videoPlayerController.setClosedCaptionFile(loadCaptions(index));
```

I use this method and it works but if only you can pass it through `meeduPlayerController`

**Comment by zezo357** [comment]
Yes will do so in next release, thank you
