### ISSUE TITLE
Incorrect size on desktop

### ISSUE THREAD

**Issue by krida2000** [zezo357/flutter_meedu_videoplayer#112]
On desktop `MeeduPlayerController.videoPlayerController.value.size` is always 1920/1080. There is the way to get actual size using `media_kit` https://github.com/alexmercerind/media_kit/issues/212.

**Comment by zezo357** [comment]
It should be the same as the logs of media_kit

**Comment by krida2000** [comment]
I investigated problem, it is hapend only when video has `heigth: 1920` and `width: 1080`

![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/71345244/c8ff7c91-1780-4aef-9167-cac97c50bcaf)

On left side is video on web and on right side is same video on Windows.


https://github.com/zezo357/flutter_meedu_videoplayer/assets/71345244/d18760cd-7cd6-435e-b241-06f09b690b49

Also attach video with what you can test it.

**Comment by zezo357** [comment]
> I investigated problem, it is hapend only when video has `heigth: 1920` and `width: 1080`
> 
> <details>
>   <summary>Image</summary>
>   
>  ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/71345244/c8ff7c91-1780-4aef-9167-cac97c50bcaf)
>  </details>
> 
> 
> On left side is video on web and on right side is same video on Windows.
> 
> <details>
>   <summary>Video</summary>
>   
> https://github.com/zezo357/flutter_meedu_videoplayer/assets/71345244/d18760cd-7cd6-435e-b241-06f09b690b49
>  </details>
> 
> Also attach video with what you can test it.
> 

I don't see the problem, the video is 1920/1080 and the size shows that

This the right logic!? 

Where is the problem?

**Comment by krida2000** [comment]
On Windows video I attached has `MeeduPlayerController.videoPlayerController.value.size.width = 1920` but its actual `width = 1080` and `MeeduPlayerController.videoPlayerController.value.size.heigth = 1080` but its actual `heigth = 1920`.

**Comment by zezo357** [comment]
Okay got you, they are switched, 


I will recheck it and let you know, sorry for that mistake and I hope I find a fix for it

**Comment by zezo357** [comment]
I may check it at night due to being busy right now sorry for that too
