### ISSUE TITLE
Background for subtitle

### ISSUE THREAD

**Issue by sommye-ctr** [zezo357/flutter_meedu_videoplayer#113]
Is it possible to enable or disable the black background on subtitles? 
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/71683523/05c82fc8-6f4b-49fd-9927-df16d1adf3e6)

**Comment by micodev** [comment]
@zezo357 I hope that you make it also customizable at runtime 
`ClosedCaption` it can be achieved with valueListenable or through meedu state management
I have a question tho,  is it going to be any time soon ? (I'm relying on it)

**Comment by micodev** [comment]
you can also rely on `https://github.com/jhomlala/betterplayer/blob/master/lib/src/subtitles/better_player_subtitles_factory.dart` for fully customized factory subtitle

**Comment by zezo357** [comment]
> @zezo357 I hope that you make it also customizable at runtime 
> `ClosedCaption` widget, it can be achieved with valueListenable or through meedu state management
> I have a question tho,  is it going to be any time soon ? (I'm relying on it)

I can make it customizable, and you can handle on run time the customization, since it will be based on each person use case

**Comment by zezo357** [comment]
If you can provide a pr that will help me greatly, since I am busy with some work. And will try to do it when I have free time

**Comment by zezo357** [comment]
fixed in `4.2.11-dev-8`, check and let me know 

also you can check the examples 
https://github.com/zezo357/flutter_meedu_videoplayer/blob/master/package/example/lib/pages/custom_subtitles.dart

**Comment by sommye-ctr** [comment]
Thanks for the quick merge man :⁠-⁠)
