### ISSUE TITLE
Disable gestures (?)

### ISSUE THREAD

**Issue by sommye-ctr** [zezo357/flutter_meedu_videoplayer#115]
Does the player support turning off the gestures? I'm passing custom widget and also setting the controls style to custom but still the gestures are on.

Actually I'm trying to implement my own focusable widgets and therefore require focus childs but when passing the custom widget it the key presses are not passed to my custom widget. Is there a way to implement this?

**Comment by sommye-ctr** [comment]
Im passing the controls in the `customControls` parameter.

The widget passed is a scaffold which covers the entire screen showing various components (seekbar title etc). There is also RawkeyboardListener but the events are not passed there (maybe the controls of the player doesnt allow traversal of focus?). Also I have set `excludeFocus` to false.

**Comment by zezo357** [comment]
> Im passing the controls in the `customControls` parameter.
> 
> The widget passed is a scaffold which covers the entire screen showing various components (seekbar title etc). There is also RawkeyboardListener but the events are not passed there (maybe the controls of the player doesnt allow traversal of focus?). Also I have set `excludeFocus` to false.

can you share an example? to be able to help you better?

since you did all the right things..

**Comment by sommye-ctr** [comment]
The top hierarchy is this and then there are just rows and columns for the widgets

`
    @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(

      focusNode: focusNode,
      onKey: _onKey,
      child: Observer(
        builder: (context) {
          if (playerStore.showControls) {
            return Stack(
              children: [
                Container(
                  height: double.infinity,
                  width: double.infinity,
                  color: Colors.black54,
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Stack(
                    children: [
                      Align(
                        alignment: Alignment.topCenter,
                        child: _buildHeading(),
                      ),
                      _buildProgressControlsRow(),
                      if (playerStore.buffering)
                        Center(
                          child: CircularProgressIndicator(),
                        ),
                    ],
                  ),
                ),
              ],
            );
          }
          return Container();
        },
      ),
    );
  }`

**Comment by zezo357** [comment]
> The top hierarchy is this and then there are just rows and columns for the widgets
> 
> ` @OverRide Widget build(BuildContext context) { return RawKeyboardListener(
> 
> ```
>   focusNode: focusNode,
>   onKey: _onKey,
>   child: Observer(
>     builder: (context) {
>       if (playerStore.showControls) {
>         return Stack(
>           children: [
>             Container(
>               height: double.infinity,
>               width: double.infinity,
>               color: Colors.black54,
>             ),
>             Padding(
>               padding: const EdgeInsets.all(8.0),
>               child: Stack(
>                 children: [
>                   Align(
>                     alignment: Alignment.topCenter,
>                     child: _buildHeading(),
>                   ),
>                   _buildProgressControlsRow(),
>                   if (playerStore.buffering)
>                     Center(
>                       child: CircularProgressIndicator(),
>                     ),
>                 ],
>               ),
>             ),
>           ],
>         );
>       }
>       return Container();
>     },
>   ),
> );
> ```
> 
> }`

can you provide an example i can run? since i need to test it to know what the problem

**Comment by sommye-ctr** [comment]
I'll provide one in few hours

**Comment by sommye-ctr** [comment]
Hey, I think I found what is causing this. By setting `excludeFocus` to false, the `ExcludeFocus` widget [here](https://github.com/zezo357/flutter_meedu_videoplayer/blob/f2a3083f754c401077fbc867946d6da675db76d0/package/lib/src/widgets/meedu_video_player.dart#L148l) sets its `excluding` property to false.

But still the `customWidget` is passed as a descendant of `ControlsContainer`, [here](https://github.com/zezo357/flutter_meedu_videoplayer/blob/f2a3083f754c401077fbc867946d6da675db76d0/package/lib/src/widgets/meedu_video_player.dart#L210l). This `ControlsContainer` hinders in events in rawKeyboardListener (I'm not sure how). 

Maybe we could change this behavior of always passing it to the `ControlsContainer` to something like passing it only when `ControlsStyle` is not custom.

**Comment by zezo357** [comment]
Do you think you can provide a pr with your idea, which does not break existing code? 
If you can I would love it, since I still don't get the problem

**Comment by sommye-ctr** [comment]
Also if i set `enabledControls` to false and then pass the widgets in the following way:

`
return Stack(

      children: [
        MeeduVideoPlayer(
          controller: controller,
          customCaptionView: (context, controller, responsive, text) {
            return Container(
              color: subBackground ?? false ? Colors.black : Colors.transparent,
              padding: EdgeInsets.all(6),
              child: Text(
                text,
                style: TextStyle(
                  color: Colors.white,
                  fontSize: subFontSize?.toDouble() ?? 14.0,
                ),
              ),
            );
          },
        ),
        Center(
            child: Text(
          "eheyryryyry",
          style: TextStyle(fontSize: 50),
        )),
        VideoPlayerControls(
          controller: controller,
          streamUrl: streamUrl,
          stream: widget.extensionStream,
          baseModel: widget.baseModel,
          episode: widget.episode,
          season: widget.season,
          movie: widget.movie,
          show: widget.show,
          progress: widget.progress,
          id: widget.id,
          fitIndex: fitIndex,
          autoSubtitle: autoSubtitle,
          detailsStore: widget.detailsStore,
          initialDark: initalDark,
          showHistory: widget.showHistory,
        ),
      ],
    );
`

The Text and my custom Controls widget appear on  screen for a split second and then they are hidden. I'm not able to understand why is this happening (maybe the player is hiding them in some way?).

**Comment by sommye-ctr** [comment]
Can you identify as to why the above thing is happening?

**Comment by zezo357** [comment]
Also I recommend using the custom controls logic already provided by the package since it helps greatly.

Check custom controls example

**Comment by sommye-ctr** [comment]
Yeah, all the things work as expected except one thing, that is RawkeyboardListener events in the customControls widget. 

So for testing, you can basically wrap the custom controls example with a rawkeyboardListener and check if its `onKey` method is ever called. For me, the onKey method is never called and therefore i'm unable to perform some actions, I want.

**Comment by zezo357** [comment]
<img width="544" alt="image" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/25157308/34ce5e1c-6545-43c5-96b8-d934433b3803">

works as expected, keep in mind now the video_player keyboard shortcuts doesnt work since they are not getting the focus

**Comment by zezo357** [comment]
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/25157308/244642323-34ce5e1c-6545-43c5-96b8-d934433b3803.png">
> works as expected, keep in mind now the video_player keyboard shortcuts doesnt work since they are not getting the focus

<img width="1161" alt="image" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/25157308/d35bad59-e674-4b41-91ea-e9758098a9fb">

**Comment by sommye-ctr** [comment]
I have no idea why is this not working when Im running the exact same code

**Comment by zezo357** [comment]
This is why I asked for a full example, since maybe another part of the code is disabling your code

**Comment by sommye-ctr** [comment]
I think I figured out what was going wrong. Is it possible to turn off the feature where the player is automatically hiding (and showing on touch) the controls? I need to manage it on my own.

**Comment by zezo357** [comment]
> I think I figured out what was going wrong. Is it possible to turn off the feature where the player is automatically hiding (and showing on touch) the controls? I need to manage it on my own.

No sadly

**Comment by sommye-ctr** [comment]
Can it be implemented? Maybe you could direct me and Ill try looking into it

**Comment by zezo357** [comment]
> Can it be implemented? Maybe you could direct me and Ill try looking into it

Check controls setter, in the controller class, you can make a variable in the controls class 

For auto hiding controls and use it there

**Comment by sommye-ctr** [comment]
Opened #118

**Comment by zezo357** [comment]
released in `4.2.13`
