### ISSUE TITLE
Is it possible to add 'Mirror to TV'

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#116]
Mirror to TVIt is a very useful feature，Looking forward to increasing.

**Comment by zezo357** [comment]
Sadly I wasn't able to do this, since I don't understand the nature of chrome cast and other tv mirroring logics, 


If someone can provide a dart code for handling it I may be Able to implement it in the app

**Comment by sommye-ctr** [comment]
I made a modified version of a previous Chromecast package. It supports passing some metadata and few other things. 

https://github.com/sommye-ctr/video_cast

It definitely has few bugs but maybe this would give a start?

**Comment by JieNengi** [comment]
> Sadly I wasn't able to do this, since I don't understand the nature of chrome cast and other tv mirroring logics, 
> 
> 
> If someone can provide a dart code for handling it I may be Able to implement it in the app

https://pub.dev/packages/dlna_dart
I think you can take a look at this

**Comment by JieNengi** [comment]
> Sadly I wasn't able to do this, since I don't understand the nature of chrome cast and other tv mirroring logics, 
> 
> 
> If someone can provide a dart code for handling it I may be Able to implement it in the app

https://pub.dev/packages/dlna_dart
I think you can take a look at this，This package scans TV devices within the local area network and broadcasts videos to the TV.

**Comment by zezo357** [comment]
I checked dlna before and couldn't understand it fully that I am able to integrate it 


But when I have some free time I will check it again

**Comment by zezo357** [comment]
> I made a modified version of a previous Chromecast package. It supports passing some metadata and few other things. 
> 
> https://github.com/sommye-ctr/video_cast
> 
> It definitely has few bugs but maybe this would give a start?

This only works on Android?

**Comment by sommye-ctr** [comment]
> > I made a modified version of a previous Chromecast package. It supports passing some metadata and few other things.
> > https://github.com/sommye-ctr/video_cast
> > It definitely has few bugs but maybe this would give a start?
> 
> This only works on Android?

Yes it is only for android as of now

**Comment by zezo357** [comment]
> > > I made a modified version of a previous Chromecast package. It supports passing some metadata and few other things.
> > > https://github.com/sommye-ctr/video_cast
> > > It definitely has few bugs but maybe this would give a start?
> > 
> > This only works on Android?
> 
> Yes it is only for android as of now

That's a very limiting factor 😢 I guess a dart solution will be the best

**Comment by sommye-ctr** [comment]
Yeah that's true. I did try to look into the dart ones but weren't sure of them. You could take a look at some of those.

**Comment by zezo357** [comment]
> Yeah that's true. I did try to look into the dart ones but weren't sure of them. You could take a look at some of those.

i will try, but no promises since i dont have any knowledge in mirroring
