### ISSUE TITLE
Making changes to the package functionality

### ISSUE THREAD

**Issue by Prince-of-death** [zezo357/flutter_meedu_videoplayer#119]
Hlo we both talked once hope you know me, what i want to say is media kit will soon get web support too the branch has already been merged and soon @alexmercerind will make a release so there will be no need to intermingle video player and media kit package as media kit will have every functionality. There may also be a ui coming. So why dont you make this a wrapper widget for media kit widget so that media kit we can use the ui of this package. Giving it another name. Then even if media kit will get a ui you can override it with wrapping it with your package widget

**Comment by zezo357** [comment]
This is already implemented and published, https://pub.dev/packages/flutter_meedu_media_kit

Hope you enjoy it, thank you very much


Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.

**Comment by alexmercerind** [comment]
package:media_kit will get it's own in-house video controls before 1.0.0 (expect by the end of this month), one of our customers need it. Default highly customizable: material, cupertino etc. controls for usage. Following is a video showing Material controls that package:media_kit will get (WIP):

https://github.com/zezo357/flutter_meedu_videoplayer/assets/28951144/a411e0bf-dc6e-44a9-819e-e06619253ec1

As you can see, the controls look very similar to YouTube.

I like stability & quality. package:media_kit is not 1.0.0 yet. I only put out stable code. Current focus has been on adding more unit tests & ensuring a stable ground before moving ahead, to enjoy a steady ride.

I have no control over whatever the people on the internet do. A stable release from my end should render (possibly) this package redundant. This package present(s) work-in-progress state work in package:media_kit as their own research. I hold no accountability for this.

Also, please refrain from ping-ing me; contact through e-mail or Discord etc.

**Comment by zezo357** [comment]
> package:media_kit will get it's own in-house video controls before 1.0.0 (expect by the end of this month), one of our customers need it. Default highly customizable: material, cupertino etc. controls for usage. Following is a video showing Material controls that package:media_kit will get (WIP):
> 
> https://github.com/zezo357/flutter_meedu_videoplayer/assets/28951144/a411e0bf-dc6e-44a9-819e-e06619253ec1
> 
> As you can see, the controls look very similar to YouTube.
> 
> I like stability & quality. package:media_kit is not 1.0.0 yet. I only put out stable code. Current focus has been on adding more unit tests & ensuring a stable ground before moving ahead, to enjoy a steady ride. On the other hand, having a good public API & architecture that industry can rely on is whole another challenge.
> 
> I have no control over whatever the people on the internet do. A stable release from my end should render (possibly) this package redundant. This package uses package:media_kit in it's work-in-progress state. I hold no accountability for this, or any issues which get surfaced due to this.
> 
> Also, please refrain from ping-ing me; contact through e-mail or Discord etc.
> 

In my case I am only releasing the package since I use it in the current state, would love to only use media_kit when it's stable and controls are included and customizable.

Thank you very much for your work.

**Comment by Prince-of-death** [comment]
> This is already implemented and published, https://pub.dev/packages/flutter_meedu_media_kit
> 
> Hope you enjoy it, thank you very much
> 
> Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.

what i mean by that is after the media_kit gets web functionality you can just modify your code such that we can wrap media kit video widget with your package so you wont need to import any of media kit in your package just the ui and you can access the player of the child video vidget and do all the volume ui, progress bar etc.

**Comment by zezo357** [comment]
> > This is already implemented and published, https://pub.dev/packages/flutter_meedu_media_kit
> > 
> > Hope you enjoy it, thank you very much
> > 
> > Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.
> 
> what i mean by that is after the media_kit gets web functionality you can just modify your code such that we can wrap media kit video widget with your package so you wont need to import any of media kit in your package just the ui and you can access the player of the child video vidget and do all the volume ui, progress bar etc.

Yes the package I mentioned, is using only media_kit, 

And wrapping the video player with this package controls

**Comment by Prince-of-death** [comment]
> > > This is already implemented and published, https://pub.dev/packages/flutter_meedu_media_kit
> > > Hope you enjoy it, thank you very much
> > > Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.
> > 
> > 
> > what i mean by that is after the media_kit gets web functionality you can just modify your code such that we can wrap media kit video widget with your package so you wont need to import any of media kit in your package just the ui and you can access the player of the child video vidget and do all the volume ui, progress bar etc.
> 
> Yes the package I mentioned, is using only media_kit,
> 
> And wrapping the video player with this package controls

It should look something like

import 'package: flutter_meedu_video_player';
meedu_video_ui(
  child: Mediakitvideo(
    player: player;
  ),
)

OR

import 'package: flutter_meedu_video_player';
Mediakitvideo(
  player: player,
  ui: custommeedui,
)
this needs media kit to implement ui functionality

**Comment by zezo357** [comment]
> > > > This is already implemented and published, https://pub.dev/packages/flutter_meedu_media_kit
> > > > Hope you enjoy it, thank you very much
> > > > Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.
> > > 
> > > 
> > > what i mean by that is after the media_kit gets web functionality you can just modify your code such that we can wrap media kit video widget with your package so you wont need to import any of media kit in your package just the ui and you can access the player of the child video vidget and do all the volume ui, progress bar etc.
> > 
> > Yes the package I mentioned, is using only media_kit,
> > 
> > And wrapping the video player with this package controls
> 
> It should look something like
> 
> import 'package: flutter_meedu_video_player';
> meedu_video_ui(
>   child: Mediakitvideo(
>     player: player;
>   ),
> )
> 
> OR
> 
> import 'package: flutter_meedu_video_player';
> Mediakitvideo(
>   player: player,
>   ui: custommeedui,
> )
> this needs media kit to implement ui functionality

I am trying to maintain the same interface for both versions of the package

So I do that internally in both cases

So yeah it's implemented like this, but internally

**Comment by alexmercerind** [comment]
> Hey dont hard code it into the main package or add a functionality so that we can use our own fully customizable ui that we provide that overrides the whole default ui. An example for this is [https://pub.dev/packages/flutter_swiper_view](url) this package gives the functionality to override its whole default ui

Who are you? I don't need your teaching or guidance to write & architecture code.

**Comment by Prince-of-death** [comment]
> > Pip is not yet released there, keep in mind web support by media_kit may not support playing hls, while we can use the video_player web hls package here.

sorry i for much confusion this is what i said

**Comment by alexmercerind** [comment]
It's better not to release something instead of publishing a buggy & incorrect implementation. Expect a 1.0.0 update before this month :) Let's allow me to work in peace. There are far bigger customers which I'm aiming for. I want to meet a level of quality.

As for video controls, I want them to LOOK GOOD, meet a standard, and follow the same principles as Flutter. See:

https://gist.github.com/alexmercerind/b228883a09cb6ec275df4a12a03227bd

You can reach us on our Discord for any updates. And... sorry I can't endorse this package, not good enough.

**Comment by alexmercerind** [comment]
And.. no we can't depend upon another package `video_player_hls`. It internally uses [`HLS.js`](https://github.com/video-dev/hls.js/), which we will use.

package:media_kit provides out-of-box support for playlists, which these packages don't.

**Comment by zezo357** [comment]
> It's better not to release something instead of publishing a buggy & incorrect implementation. Expect 1.0.0 release of package:media_kit before this month :) Let's allow me to work in peace. There are far bigger customers which I'm aiming for. I want to meet a level of quality.
> 
> As for video controls, I want them to LOOK GOOD, meet a standard, and follow the same principles as Flutter. See:
> 
> https://gist.github.com/alexmercerind/b228883a09cb6ec275df4a12a03227bd
> 
> You can reach us on our Discord for any updates. And... sorry I can't endorse this package, not good enough.

Looks very good and easy to use, thank you for your awesome work.
