### ISSUE TITLE
[Android] when back from full screen mode ,the controller dispose !

### ISSUE THREAD

**Issue by Joseph-Nathan** [zezo357/flutter_meedu_videoplayer#12]
when back from full screen mode ,the controller dispose ,
and the video stoped ,
meeduController.videoPlayerController wil be null ?

**Comment by zezo357** [comment]
Yes and If you used the same meeduController a new video player controller will be initialized

**Comment by Joseph-Nathan** [comment]
i do not change any controller , and do as example , 
who can i solve it .

**Comment by zezo357** [comment]
- I don't understand the problem!

**Comment by Joseph-Nathan** [comment]
in `MeeduPlayerFullscreenPage`
i comment 
``` @override
  Future<void> dispose() async {
    print("disposed");
    this.widget.controller.videoPlayerClosed();
    super.dispose();
  }```
and it work fine ,

and in `` file , in `goToFullscreen` function ,
i replace this code 
```
    final route = MaterialPageRoute(
      builder: (_) {
        return MeeduPlayerFullscreenPage(controller: this);
      },
    );
```
by this 
```
    final route = PageRouteBuilder(
      opaque: false,
      fullscreenDialog: true,
      pageBuilder: (_, __, ___) {
        return MeeduPlayerFullscreenPage(controller: this);
      },
    );
```
because i used waterMark animated widget  overlay on the player , and it stopped in fullscreen mode ,

**Comment by zezo357** [comment]
@Joseph-Nathan I really don't understand what is the problem, can you please give an example of your code or your problem

With the steps to reproduce?

**Comment by Joseph-Nathan** [comment]
problem 1 : 
 - controller dispose after return from FullScreen mode , and can n't be used again .
 reproduce : 
1- go to play widget 
2- go to Fullscreen mode 
3- go back to normal mode 
4- try to play the video ,
how to solve this : 
in `fullscreen_page` file , in `MeeduPlayerFullscreenPage` class
replace this code 
```
  @override
  Future<void> dispose() async {
    print("disposed");
    this.widget.controller.videoPlayerClosed();
    super.dispose();
  }
```
to this : 
```
  @override
  Future<void> dispose() async {
    print("disposed");
    this.widget.controller.onFullscreenClose();
    super.dispose();
  }
```
and add `onFullscreenClose` function in `controller`
```
  Future<void> onFullscreenClose( [AsyncCallback? restoreHotkeysCallback] ) async {
    fullscreen.value = false;
    resetBrightness();
    if (windows) {
      screenManager.setWindowsFullScreen(false, this);
      HotKeyManager.instance
          .unregisterAll()
          .then((value) => restoreHotkeysCallback?.call());
    } else {
      screenManager.setDefaultOverlaysAndOrientations();
    }
  }
```
problem 2 : 
 - i used animated overlay above the player widget as watermark ,
 - it's work fine in normal mode but when go to full screen the animated stop and the waterMark widget freeze in the screen 
 - if you would to provide 2 video before/after for this problem , it will be ok ,
 how to solve this : 
in `controller` file , in `goToFullscreen` Function , replace  this code 
``` final route = MaterialPageRoute(
      builder: (_) {
        return MeeduPlayerFullscreenPage(controller: this);
      },
    ); 
```
to this 
```
    final route = PageRouteBuilder(
      opaque: false,
      fullscreenDialog: true,
      pageBuilder: (_, __, ___) {
        return MeeduPlayerFullscreenPage(controller: this);
      },
    );
```

problem 3 : 
 - it's not good to provide all BoxFit to user , can you pass fits in controller 
```
  List<BoxFit> fits = [
    BoxFit.contain,
    BoxFit.cover,
    BoxFit.fill,
    BoxFit.fitHeight,
    BoxFit.fitWidth,
    BoxFit.scaleDown
  ];
```

**Comment by zezo357** [comment]
> problem 1 : 
>  - controller dispose after return from FullScreen mode , and can n't be used again .
>  reproduce : 
> 1- go to play widget 
> 2- go to Fullscreen mode 
> 3- go back to normal mode 
> 4- try to play the video ,
> how to solve this : 
> in `fullscreen_page` file , in `MeeduPlayerFullscreenPage` class
> replace this code 
> ```
>   @override
>   Future<void> dispose() async {
>     print("disposed");
>     this.widget.controller.videoPlayerClosed();
>     super.dispose();
>   }
> ```
> to this : 
> ```
>   @override
>   Future<void> dispose() async {
>     print("disposed");
>     this.widget.controller.onFullscreenClose();
>     super.dispose();
>   }
> ```
> and add `onFullscreenClose` function in `controller`
> ```
>   Future<void> onFullscreenClose( [AsyncCallback? restoreHotkeysCallback] ) async {
>     fullscreen.value = false;
>     resetBrightness();
>     if (windows) {
>       screenManager.setWindowsFullScreen(false, this);
>       HotKeyManager.instance
>           .unregisterAll()
>           .then((value) => restoreHotkeysCallback?.call());
>     } else {
>       screenManager.setDefaultOverlaysAndOrientations();
>     }
>   }
> ```
> problem 2 : 
>  - i used animated overlay above the player widget as watermark ,
>  - it's work fine in normal mode but when go to full screen the animated stop and the waterMark widget freeze in the screen 
>  - if you would to provide 2 video before/after for this problem , it will be ok ,
>  how to solve this : 
> in `controller` file , in `goToFullscreen` Function , replace  this code 
> ``` final route = MaterialPageRoute(
>       builder: (_) {
>         return MeeduPlayerFullscreenPage(controller: this);
>       },
>     ); 
> ```
> to this 
> ```
>     final route = PageRouteBuilder(
>       opaque: false,
>       fullscreenDialog: true,
>       pageBuilder: (_, __, ___) {
>         return MeeduPlayerFullscreenPage(controller: this);
>       },
>     );
> ```
> 
> problem 3 : 
>  - it's not good to provide all BoxFit to user , can you pass fits in controller 
> ```
>   List<BoxFit> fits = [
>     BoxFit.contain,
>     BoxFit.cover,
>     BoxFit.fill,
>     BoxFit.fitHeight,
>     BoxFit.fitWidth,
>     BoxFit.scaleDown
>   ];
> ```
> 
> 
> 
> 
> 

Thank you for the explanation would you like to make a pull request with the fixes so I apply them?

**Comment by zezo357** [comment]
If you can't make a pull request just let me know and I will try to fix it as soon as possible

**Comment by Joseph-Nathan** [comment]
i will do that ,
forward & rewind icons , work in fullscreen mode ,but does n't work in normal mode ?
i try to see why but stuck , where should search ?

**Comment by zezo357** [comment]
Controls container is handling swipes  if remember correctly
 https://github.com/zezo357/flutter_meedu_videoplayer/blob/master/lib/src/widgets/styles/primary/primary_player_controls.dart

Is the location of the primary controls
