### ISSUE TITLE
Subtitles consistency issue

### ISSUE THREAD

**Issue by sommye-ctr** [zezo357/flutter_meedu_videoplayer#120]
When there are consecutive dialogs in the Subtitle file, the subtitles are sometimes shown and sometimes not. An example of this is attached below. 

Also this is majorly seen in vtt files and am not able to completely reproduce this on srt files so cannot say for sure on them.

Uploading VID_20230616_173714_239.mp4…

**Comment by zezo357** [comment]
I think the video didn't get uploaded correctly, sadly the parsing for subtitles is handled by video_player package

Incase you were able to pinpoint the main cause I may try to open a pr in video_player fixing it, other than that sadly I won't be able to do much

**Comment by sommye-ctr** [comment]
https://github.com/zezo357/flutter_meedu_videoplayer/assets/71683523/9145196c-e61b-4397-87f2-795b1d9cfe3b

This is the video. Sadly I am not able to pinpoint the error. Could this be possible because the I'm using media kit enabled. The video is managed by the media kit library but the Subtitles by video player?

**Comment by zezo357** [comment]
> 
> https://github.com/zezo357/flutter_meedu_videoplayer/assets/71683523/9145196c-e61b-4397-87f2-795b1d9cfe3b
> 
> This is the video. Sadly I am not able to pinpoint the error. Could this be possible because the I'm using media kit enabled. The video is managed by the media kit library but the Subtitles by video player?
> 
Subtitles are managed by video_video but it's written in dart,

So using with media_kit or without it should make no difference

**Comment by zezo357** [comment]
From my point of view, I guess we will need to make sure the subtitle file is correct before we can further test it 

It you can provide the subtitles file that's will be awesome

**Comment by sommye-ctr** [comment]
Here is an example of vtt file and I can confirm that the above problem is with this too

https://cc.2cdns.com/e5/d2/e5d22a99e52793d944a3723916646865/eng-4.vtt

**Comment by zezo357** [comment]
i believe  the subtitles are the ones with the problem here, i cant find the words spoken in the subtitle files

**Comment by sommye-ctr** [comment]
No it's not the same subtitle file as in the video attached. It's a different subtitle file but it too has problems. Whenever I run with the attached subtitle file, the words which are actually in the file are not shown

**Comment by zezo357** [comment]
Please provide a full example, since I can't check it like this 😢

**Comment by micodev** [comment]
https://github.com/zezo357/flutter_meedu_videoplayer/assets/17555698/c4d62387-3d5f-483a-9efc-74f45f258c2b


related to subtitle , the custom subtitle widget not works when changing orientation of the player using button provided.

**Comment by zezo357** [comment]
> 
> https://github.com/zezo357/flutter_meedu_videoplayer/assets/17555698/c4d62387-3d5f-483a-9efc-74f45f258c2b
> 
> 
> related to subtitle , the custom subtitle widget not works when changing orientation of the player using button provided.

Ok, that's possible to check, will check it and let you know


You are reproduce this using the examples provided right?

**Comment by Thiagobhmg** [comment]
It would be ideal for the player to support VTT subtitles instead of SRT. VTT is the standard format for online videos and can be used with players like VIDEO.JS.

**Comment by zezo357** [comment]
If video_player supports it then it's supported, if you can to test it and let me know if it works. That will be much appreciated

**Comment by zezo357** [comment]
> Record_2023-06-16-21-03-40.mp4 
> related to subtitle , the custom subtitle widget not works when changing orientation of the player using button provided.

4.2.14 is released.
