### ISSUE TITLE
error in source after publish to google play

### ISSUE THREAD

**Issue by micodev** [zezo357/flutter_meedu_videoplayer#122]
![IMG_20230619_114925_417](https://github.com/zezo357/flutter_meedu_videoplayer/assets/17555698/8bb70c35-186a-44e9-8410-62b8c98698a5)

I get this error when I run the video ,
when I change the resolution it works.

what is this problem ?

**Comment by zezo357** [comment]
Most probably it's a source error, like when you choose the same quality again does it work?

From what I am seeing it's not a package bug it's a source bug.


Btw nice layout for the controls, I think the package should add more layouts as defaults, to make it easier on people that don't want to make custom layouts ,if you want to add it to the package, let me know or open a pr for it

**Comment by micodev** [comment]
when I re select same quality it work , only first time.

**Comment by micodev** [comment]
> Most probably it's a source error, like when you choose the same quality again does it work?
> 
> From what I am seeing it's not a package bug it's a source bug.
> 
> Btw nice layout for the controls, I think the package should add more layouts as defaults, to make it easier on people that don't want to make custom layouts ,if you want to add it to the package, let me know or open a pr for it

thanks for mentioning the layout I overwrite the controls , I hope to help but with this project I am using Get package as statement management, so shifting to another one will take time , I can start open an pr for those layouts when I finished , I published it yesterday but suddenly this error come up after publishing (it occurs on bundle version when I use release apk all things fine).

**Comment by zezo357** [comment]
> when I re-select same quality it work , only first time doesn't.

lets check

in debug everything works correctly right?

you are using video_player? did you try to enable media_kit?

does only happen at first launch of any video in app, or any video will get this error and you have to choose another quality (if only first video in general (it may be video_player problem))
 

can you share code so i can test with you (even if private)?

**Comment by zezo357** [comment]
> > Most probably it's a source error, like when you choose the same quality again does it work?
> > From what I am seeing it's not a package bug it's a source bug.
> > Btw nice layout for the controls, I think the package should add more layouts as defaults, to make it easier on people that don't want to make custom layouts ,if you want to add it to the package, let me know or open a pr for it
> 
> thanks for mentioning the layout I overwrite the controls , I hope to help but with this project I am using Get package as statement management, so shifting to another one will take time , I can start open an pr for those layouts when I finished , I published it yesterday but suddenly this error come up after publishing (it occurs on bundle version when I use release apk all things fine).

the layout doesn't need to use get, just the placement of the slider and the other widgets is good. (like the package needs to only include the placements of the widgets and people can customize however they like)

**Comment by zezo357** [comment]
> > > when I re-select same quality it work , only first time doesn't.
> > 
> > lets check
> > 
> > in debug everything works correctly right?
> > 
> > you are using video_player? did you try to enable media_kit?
> > 
> > does only happen at first launch of any video in app, or any video will get this error and you have to choose another quality (if only first video in general (it may be video_player problem))
> > 
> > can you share code so i can test with you (even if private)?
> 
> let me try to reproduce the issue from my debug session then tell you , I am not using media_kit bc of the problem of re-seeking drawing not smooth 🥹 ( the problem of seek not painting )
> 
> 
> even if I share the code to you ( the source is over private ip that only belongs to ISP )

Didn't we solve the seeking problem?

**Comment by zezo357** [comment]
> > > > > when I re-select same quality it work , only first time doesn't.
> > > > 
> > > > 
> > > > lets check
> > > > in debug everything works correctly right?
> > > > you are using video_player? did you try to enable media_kit?
> > > > does only happen at first launch of any video in app, or any video will get this error and you have to choose another quality (if only first video in general (it may be video_player problem))
> > > > can you share code so i can test with you (even if private)?
> > > 
> > > 
> > > let me try to reproduce the issue from my debug session then tell you , I am not using media_kit bc of the problem of re-seeking drawing not smooth 🥹 ( the problem of seek not painting )
> > > even if I share the code to you ( the source is over private ip that only belongs to ISP )
> > 
> > Didn't we solve the seeking problem?
> 
> it has one or two frame and it jumps ( looks weird ) that's why I am not using it .

Yeah that's due to my workaround, will check if I can make it better

**Comment by zezo357** [comment]
> I fixed the problem the issue was when I defining video format manually , I used `dash type` for videos then the issue occurs 

Oh, glad you got it fixed
