### ISSUE TITLE
Exoplayer error (android) when I try to start HLS

### ISSUE THREAD

**Issue by 0Franky** [zezo357/flutter_meedu_videoplayer#128]
Hi @zezo357,
I'm trying to playing a hls via url but I'm retrieving this error:
![immagine](https://github.com/zezo357/flutter_meedu_videoplayer/assets/48295794/890ec94d-edbb-4ff0-a651-cb2bcde7012d)

The m3uu8 file starts as follow:
#EXTM3U  
#EXT-X-VERSION:3  
#EXT-X-TARGETDURATION:6  
#EXT-X-MEDIA-SEQUENCE:0  
#EXT-X-PLAYLIST-TYPE:VOD  
#EXTINF:5.760000,  
url1  
#EXTINF:3.840000,  
url2  
#EXTINF:3.840000,  
url3  
...

Can you help me?

**Comment by zezo357** [comment]
I recommend enabling media_kit looks like it's a  video_player error, see if that fixes the problem

**Comment by 0Franky** [comment]
With media_kit it works, thank you! :)
