### ISSUE TITLE
Video not showing up in release

### ISSUE THREAD

**Issue by machadoguilhermebr** [zezo357/flutter_meedu_videoplayer#130]
Hi!

In debug mode everything works as expected.
Once the website is deployed the video doesn't show and only a white square appears.

UnimplementedError: init() has not been inplemented

even though I started in main

Any help?

**Comment by zezo357** [comment]
I don't know what the problem and how to reproduce it, 

Please provide code to reproduce the problem 

(Like a GitHub repo )
