### ISSUE TITLE
macos Initialization window size issue

### ISSUE THREAD

**Issue by 1124863805** [zezo357/flutter_meedu_videoplayer#131]
fisrt 

<img width="1119" alt="截屏2023-07-02 00 25 47" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/31816203/6eb23801-c460-410c-8d35-d350f4dad6ce">

then

<img width="1273" alt="截屏2023-07-02 00 25 54" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/31816203/3f1c23e8-5b90-4c0d-9883-8463ae339b56">

The above is an example of using a plugin

If I use a third-party plugin and specify the window size, the above situation will still occur

such as

  bitsdojo_window: ^0.1.5

` doWhenWindowReady(() {
        const initialSize = Size(1000, 800);
        appWindow.minSize = initialSize;
        appWindow.size = initialSize;
        appWindow.alignment = Alignment.center;
        appWindow.show();
      });`

The size shown in Figure 2 will still appear, but it will return to normal next time it starts

**Comment by zezo357** [comment]
Well that's weird, can you provide an example code to reproduce the problem?

**Comment by 1124863805** [comment]
https://github.com/zezo357/flutter_meedu_videoplayer/tree/master/package/example

in macos Your official example can be reproduced

**Comment by zezo357** [comment]
> https://github.com/zezo357/flutter_meedu_videoplayer/tree/master/package/example
> 
> in macos Your official example can be reproduced

Will test and let you know, keep in mind I am busy these days, so when I have time I will test

**Comment by westito** [comment]
Same here. The problem is the `initMeeduPlayer()` call. Why it is setting window size? 

```
Future<void> initWindowManagerIfNeeded() async {
  if (UniversalPlatform.isDesktop) {
    await windowManager.ensureInitialized();

    WindowOptions windowOptions = const WindowOptions(
      size: Size(1200, 700),
      center: true,
    );

    windowManager.waitUntilReadyToShow(windowOptions, () async {
      await windowManager.show();
      await windowManager.focus();
    });
  }
}```

**Comment by zezo357** [comment]
> Same here. The problem is the `initMeeduPlayer()` call. Why it is setting window size?
> 
> ```
> Future<void> initWindowManagerIfNeeded() async {
>   if (UniversalPlatform.isDesktop) {
>     await windowManager.ensureInitialized();
> 
>     WindowOptions windowOptions = const WindowOptions(
>       size: Size(1200, 700),
>       center: true,
>     );
> 
>     windowManager.waitUntilReadyToShow(windowOptions, () async {
>       await windowManager.show();
>       await windowManager.focus();
>     });
>   }
> }```
> ```

its because of the pip feature, we can add a boolean to disable it if not needed

**Comment by westito** [comment]
Absolutely need :D I use auto window restoration that maintains the last window size

**Comment by zezo357** [comment]
4.2.14 is released.
