### ISSUE TITLE
I get this error while play HLS video on Android Emulator

### ISSUE THREAD

**Issue by namdroid** [zezo357/flutter_meedu_videoplayer#134]
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): Failed to handle method call
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): java.lang.ClassCastException: com.example.smarttv_flutter_poc.MainActivity cannot be cast to com.zezo357.flutter_meedu_videoplayer.MeeduPlayerFlutterActivity
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at com.zezo357.flutter_meedu_videoplayer.FlutterMeeduVideoplayerPlugin.initPipConfiguration(FlutterMeeduVideoplayerPlugin.java:74)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at com.zezo357.flutter_meedu_videoplayer.FlutterMeeduVideoplayerPlugin.onMethodCall(FlutterMeeduVideoplayerPlugin.java:51)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#com.zezo357.flutter_meedu_videoplayer( 5627): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by zezo357** [comment]
Please provide your mobile phone model and flutter doctor, also confirm with me is it limited to only hls?


Does enabling media_kit solves it?

**Comment by namdroid** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-x64, locale de-DE)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.1/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/nguyenn/Documents/flutter. Consider adding /Users/nguyenn/Documents/flutter/bin
      to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources


I have android tv emulator API 22

**Comment by namdroid** [comment]
media_kit  is enabled

**Comment by zezo357** [comment]
Can you provide an example code where it happens?
