### ISSUE TITLE
conflict with package_info_plus: ^4.0.2 and device_info_plus: ^9.0.2，dependencies version are to old.

### ISSUE THREAD

**Issue by zhaoxianxin** [zezo357/flutter_meedu_videoplayer#139]
Resolving dependencies...
Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
Because every version of flutter_meedu_videoplayer depends on wakelock ^0.6.1+2 which depends on wakelock_windows ^0.2.0, every version of flutter_meedu_videoplayer requires wakelock_windows ^0.2.0.
Thus, every version of flutter_meedu_videoplayer requires win32 ^2.0.0 or ^3.0.0.
And because package_info_plus >=4.0.1 depends on win32 >=4.0.0 <6.0.0, flutter_meedu_videoplayer is incompatible with package_info_plus >=4.0.1.
So, because workplace depends on both package_info_plus ^4.0.2 and flutter_meedu_videoplayer ^4.2.10, version solving failed.

**Comment by zezo357** [comment]
I am waiting for media_kit release for wake_lock plus so I migrate to it, for now you will have to use dependency overrides, for the packages that causes the conflict

**Comment by zezo357** [comment]
wake_lock plus is now used, and should fix the problem you were having
