### ISSUE TITLE
flutter_meedu_videoplayer: ^4.2.10  ios run failed

### ISSUE THREAD

**Issue by zhaoxianxin** [zezo357/flutter_meedu_videoplayer#140]
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `FlutterPluginRegistrant` from `Flutter/FlutterPluginRegistrant`
    -> Fetching podspec for `auto_orientation` from `.symlinks/plugins/auto_orientation/ios`
    -> Fetching podspec for `camera_avfoundation` from `.symlinks/plugins/camera_avfoundation/ios`
    -> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
    -> Fetching podspec for `flutter_meedu_videoplayer` from `.symlinks/plugins/flutter_meedu_videoplayer/ios`
    -> Fetching podspec for `media_kit_native_event_loop` from `.symlinks/plugins/media_kit_native_event_loop/ios`
    make: Nothing to be done for `all'.
    -> Fetching podspec for `media_kit_video` from `.symlinks/plugins/media_kit_video/ios`
    make: Nothing to be done for `all'.
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/darwin`
    -> Fetching podspec for `permission_handler_apple` from `.symlinks/plugins/permission_handler_apple/ios`
    -> Fetching podspec for `photo_manager` from `.symlinks/plugins/photo_manager/ios`
    -> Fetching podspec for `screen_brightness_ios` from `.symlinks/plugins/screen_brightness_ios/ios`
    -> Fetching podspec for `shared_preferences_foundation` from `.symlinks/plugins/shared_preferences_foundation/darwin`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `video_player_avfoundation` from `.symlinks/plugins/video_player_avfoundation/ios`
    -> Fetching podspec for `volume_controller` from `.symlinks/plugins/volume_controller/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "media_kit_video":
      In Podfile:
        FlutterPluginRegistrant (from `Flutter/FlutterPluginRegistrant`) was resolved to 0.0.1, which depends on
          media_kit_video

        media_kit_video (from `.symlinks/plugins/media_kit_video/ios`)

    Specs satisfying the `media_kit_video (from `.symlinks/plugins/media_kit_video/ios`), media_kit_video` dependency were found, but they required a higher minimum deployment target.

    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/tyzl/.gem/ruby/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/tyzl/.gem/ruby/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
    /Users/tyzl/.gem/ruby/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    media_kit: WARNING: package:media_kit_libs_ios_*** not found
    media_kit: WARNING: package:media_kit_libs_ios_*** not found

Exception: Error running pod install

**Comment by zezo357** [comment]
Also the documentation sets the iOS minimum version, check it from the package setup part

**Comment by andrezanna** [comment]
Hi this happenede to me too, but a pod update managed to fix the issue
