### ISSUE TITLE
Feature Request: Quality Adjustment Option for Single .m3u8 Format Videos

### ISSUE THREAD

**Issue by ArmanKubak** [zezo357/flutter_meedu_videoplayer#142]
Hello,

I believe it would be highly beneficial if there was an option to integrate a feature that enables users to adjust the quality of .m3u8 file format videos directly from the player interface.

Presently, I have noticed examples where different file formats are used to provide varying quality options. However, my suggestion relates specifically to scenarios where only one .m3u8 URL is used. I envision the video player being able to detect this URL and subsequently display a button for changing the video quality, similar to the functionality found on platforms like YouTube.

Thank you for your attention to this matter. Looking forward to your consideration.

**Comment by zezo357** [comment]
You can use the m3u8 example, why I am leaving it out of the logic, 

To avoid implementation problems due to my logic since it doesn't cover all cases, so I want it to be easier to edit the logic for all people


If you want me to improve the example let me know

**Comment by ArmanKubak** [comment]
Thanks for your explanation , I  checked the .m3u8 example its good but  I think all of that could be implemented to the plugin then with a true false value that cloud be on and off ,

**Comment by zezo357** [comment]
Will check if it will not conflict with any logics, but most probably it will not be implemented in package, the most I can do is create a handler to it

**Comment by armanhadifatah** [comment]
The .m3u8 example works fine on android , but it dose not work on ios 
inside the video player it say "Failed to load video: The operation couldn't be completed. ( CoreMediaErrorDomain error - 12865.)

**Comment by zezo357** [comment]
Did you make sure iOS application has the right permissions? Storage and internet?

Since it does create temp files for each quality, and ofcourse needs internet access to play any of them

**Comment by armanhadifatah** [comment]
I think ios do not need permissions for storage like saving temp file , and i use same exact code for android and ios , also i'm using real device not emulator , i do not get any error from flutter or ios just this : 

[flutter_meedu_videoplayer] PlatformException(VideoError, Failed to load video: The operation couldn’t be completed. (CoreMediaErrorDomain error -12865.), null, null)

**Comment by zezo357** [comment]
Seems like a general problem with video_player 

https://stackoverflow.com/questions/71154896/video-not-play-in-flutter-ios-getting-error


Check if any of those fixes it , if all fails try to enabling media_kit for iOS

**Comment by armanhadifatah** [comment]
I tried with media_kit but not working , for now i do not know what is the problem

**Comment by zezo357** [comment]
> I tried with media_kit but not working , for now i do not know what is the problem

What is the error in media_kit?
