### ISSUE TITLE
Blank screen with ESC key on Windows 11

### ISSUE THREAD

**Issue by autocar** [zezo357/flutter_meedu_videoplayer#144]
Hello,
on Windows (W11)
at the moment of "initstate"
meeduPlayerController.setFullScreen(false, context);
black screen.
or 1 time before making full screen when the player is displayed,
After making the full screen, when the ESC key is pressed 2 times, the screen becomes black again.

**Comment by zezo357** [comment]
Can you let me know the steps to reproduce it?

Or the code

**Comment by zezo357** [comment]
Also, which version are you using, and can you test on latest one?

**Comment by autocar** [comment]
Hello again,
Thank you for your answer.
The problem still persists with version 4.2.20.
If you compile the BasicExamplePage page with Windows and press ESC when it opens, the screen goes black immediately.

This is what happens when you press the ESC key.
https://github.com/zezo357/flutter_meedu_videoplayer/assets/5386491/0cb3e070-c97d-4bfc-977d-5a806b7f64ff

**Comment by zezo357** [comment]
> Hello again,
> Thank you for your answer.
> The problem still persists with version 4.2.20.
> If you compile the BasicExamplePage page with Windows and press ESC when it opens, the screen goes black immediately.
> 
> This is what happens when you press the ESC key.
> https://github.com/zezo357/flutter_meedu_videoplayer/assets/5386491/0cb3e070-c97d-4bfc-977d-5a806b7f64ff
> 
> 

Oh that's an edge case, I never tried that 

Thank you for explaining will check it when I have some free time

**Comment by autocar** [comment]
problem is controller.dart line 994
Navigator.pop(context);

**Comment by autocar** [comment]
please replace controller.dart line 994
Navigator.pop(context);
to
if (this.fullscreen.value) {
    Navigator.pop(context);
  }

no problem, i am tested.

**Comment by mobisofts** [comment]
I sent a pull request.
Thank you for this library and everything
