### ISSUE TITLE
Getting error while run in flutter 3.10.5

### ISSUE THREAD

**Issue by sanjayajena37** [zezo357/flutter_meedu_videoplayer#147]
Error: Error when reading '/Users/username/.pub-cache/hosted/pub.dev/media_kit-1.1.0/lib/src/player/libmpv/core/native_library.dart': No such file or directory
import 'package:media_kit/src/player/libmpv/core/native_library.dart';

![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/41119327/76bd423d-75b7-44a8-b5b6-fed4dd24d43d)

Please help

flutter version : 3.10.5
meedu player: 4.2.16
media_kit : 1.1.0
media_kit :1.0.2

**Comment by zezo357** [comment]
Please define the versions in pubspec, don't leave then undefined ...

And try again most probably the undefined is the problem

**Comment by sanjayajena37** [comment]
I have tried using this above version still am facing same problem:

flutter version : 3.10.5
meedu player: 4.2.16
media_kit : 1.1.0
media_kit :1.0.2

**Comment by zezo357** [comment]
> Error: Error when reading '/Users/username/.pub-cache/hosted/pub.dev/media_kit-1.1.0/lib/src/player/libmpv/core/native_library.dart': No such file or directory
> import 'package:media_kit/src/player/libmpv/core/native_library.dart';
> 
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/41119327/76bd423d-75b7-44a8-b5b6-fed4dd24d43d)
> 
> Please help
> 
> flutter version : 3.10.5
> meedu player: 4.2.16
> media_kit : 1.1.0
> media_kit :1.0.2

Let's make a deal, here flutter can't find a media_kit file

So it's a problem from pub 

As long as I don't have steps to reproduce it I can't help


And in the screenshot you don't define versions, 

And in the text I see media_kit twice 

So I am confused..

**Comment by wxjrkm520** [comment]
same problem

**Comment by wxjrkm520** [comment]
/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
r/libmpv/core/native_library.dart':

**Comment by wxjrkm520** [comment]
No libmpv folder

**Comment by zezo357** [comment]
> /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> r/libmpv/core/native_library.dart': 

Hello why using media_kit video 1.0.2?


Will check and let you know it should be 1.1.0

Can you use last version of this package and try again?

**Comment by zezo357** [comment]
Can both of you test with

`flutter_meedu_videoplayer: ^4.2.20`

**Comment by wxjrkm520** [comment]
> > /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> > r/libmpv/core/native_library.dart':
> 
> Hello why using media_kit video 1.0.2?
> 
> Will check and let you know it should be 1.1.0
> 
> Can you use last version of this package and try again?

Use the latest Flutter version
Use the latest version of the package
Solved the above issues

**Comment by zezo357** [comment]
> > > /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> > > r/libmpv/core/native_library.dart':
> > 
> > Hello why using media_kit video 1.0.2?
> > 
> > Will check and let you know it should be 1.1.0
> > 
> > Can you use last version of this package and try again?
> 
> Use the latest Flutter version
> Use the latest version of the package
> Solved the above issues
> 

Thank you for confirming.

**Comment by sanjayajena37** [comment]
Whats your flutter version? Am using 3.10.5> issues

**Comment by sanjayajena37** [comment]
> > > /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> 
> > > r/libmpv/core/native_library.dart':
> 
> > 
> 
> > Hello why using media_kit video 1.0.2?
> 
> > 
> 
> > Will check and let you know it should be 1.1.0
> 
> > 
> 
> > Can you use last version of this package and try again?
> 
> 
> 
> Use the latest Flutter version
> 
> Use the latest version of the package
> 
> Solved the above issues
> 
> 

Whats your flutter version? Am using 3.10.5 but not resolved yet

**Comment by wxjrkm520** [comment]
> Whats your flutter version? Am using 3.10.5> issues
flutter：3.10.6
flutter_meedu_videoplayer: ^4.2.20
pub upgrade

**Comment by zezo357** [comment]
> > > > /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> > 
> > > > r/libmpv/core/native_library.dart':
> > 
> > > 
> > 
> > > Hello why using media_kit video 1.0.2?
> > 
> > > 
> > 
> > > Will check and let you know it should be 1.1.0
> > 
> > > 
> > 
> > > Can you use last version of this package and try again?
> > 
> > 
> > 
> > Use the latest Flutter version
> > 
> > Use the latest version of the package
> > 
> > Solved the above issues
> > 
> > 
> 
> Whats your flutter version? Am using 3.10.5 but not resolved yet

Can you please share the pubspec where the error shows please.....

**Comment by wxjrkm520** [comment]
> > > > /E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit_video-1.0.2/lib/src/video_controller/native_video_controller/real.dart(17,8): error GFAA2A68C: Error when reading '/E:/PUB/Cache/hosted/pub.flutter-io.cn/media_kit-1.1.0/lib/src/playe
> > 
> > 
> > > > r/libmpv/core/native_library.dart':
> > 
> > 
> > > 
> > 
> > 
> > > Hello why using media_kit video 1.0.2?
> > 
> > 
> > > 
> > 
> > 
> > > Will check and let you know it should be 1.1.0
> > 
> > 
> > > 
> > 
> > 
> > > Can you use last version of this package and try again?
> > 
> > 
> > Use the latest Flutter version
> > Use the latest version of the package
> > Solved the above issues
> 
> Whats your flutter version? Am using 3.10.5 but not resolved yet

**pub upgrade**

This issue is caused by the low version of medi_kit
