### ISSUE TITLE
Embedded Subtitles and Audio track

### ISSUE THREAD

**Issue by michalss** [zezo357/flutter_meedu_videoplayer#149]
Hi,

Is there a way if video has more audio tracks and more subtitles embedded to choose it somehow please?

**Comment by zezo357** [comment]
if you are already using my package in your project

https://github.com/zezo357/flutter_meedu_media_kit

can help, its the same as this package but with controller as media_kit so you can interact with it

**Comment by michalss** [comment]
move to proper place to ask... https://github.com/zezo357/flutter_meedu_media_kit/issues/4
