### ISSUE TITLE
AFR supported ?

### ISSUE THREAD

**Issue by michalss** [zezo357/flutter_meedu_videoplayer#150]
Hi,
 Is ARF(Automatic Frame Rate) supported please ?  Mostly releated to mobile platforms..
 
` AFR (auto frame rate) – is function which designed to match the media player's output frame rate to the original frame rate of (video) content. This applies to content that's mastered at different frame rates, for example 24fps film-based content or other international video content encoded at 60, 50, 30, 25, and 24fps.`

Some more exmaplanation why is needed.. 
https://tvbox-app.com/en/autoframerate/
https://ugoos.com/system-auto-frame-rate-for-tv-boxes

Regards

**Comment by zezo357** [comment]
I use video_player and media_kit for playback


So if they support it I do,


The problem is I don't know if they support it or not 😞

**Comment by michalss** [comment]
it should support it as using mpv as base..
