### ISSUE TITLE
onDoubleTap should add pause playback and resume playback

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#152]
I tried to use it, but it doesn't work when going to full screen. 

`AspectRatio(
                        aspectRatio: 16 / 9,
                        child: GestureDetector(
                          onDoubleTap: () {
                            if (_controller.playerStatus.playing) {
                              _controller.pause();
                            } else {
                              _controller.play();
                            }
                          },
                          child: MeeduVideoPlayer(
                            controller: _controller,
                          ),
                        ),
                      )`

**Comment by zezo357** [comment]
> I tried to use it, but it doesn't work when going to full screen. 
> 
> `AspectRatio(
>                         aspectRatio: 16 / 9,
>                         child: GestureDetector(
>                           onDoubleTap: () {
>                             if (_controller.playerStatus.playing) {
>                               _controller.pause();
>                             } else {
>                               _controller.play();
>                             }
>                           },
>                           child: MeeduVideoPlayer(
>                             controller: _controller,
>                           ),
>                         ),
>                       )`

You are wrapping the main screen not the Fullscreen too,

**Comment by zezo357** [comment]
in 4.2.24
 you can add the overlay like this, will work on both fullscreen and normal mode
 
 ```
 MeeduVideoPlayer(
            controller: _meeduPlayerController,
            videoOverlay: (context, controller, responsive) => Container(
              color: Colors.red,
              child: SizedBox(
                height: 50,
                width: 50,
              ),
            ),
            header: (context, controller, responsive) => header,
          ),
 ```
