### ISSUE TITLE
How to add Overlay in player. I want to add watermarks, it is working in normal screen but not appearing when full screen. 

### ISSUE THREAD

**Issue by vcshivani** [zezo357/flutter_meedu_videoplayer#154]
`Stack(
        children: [
          MeeduVideoPlayer(
            controller: _meeduPlayerController,
          ),
          ...widget.watermarkTexts.map((text) {
            return WatermarkLayover(text: text);
          }).toList(),
        ],
      );`

**Comment by zezo357** [comment]
Well that is hard in full screen, but you can define custom controls with the overlay on it , which will work on both modes

**Comment by vcshivani** [comment]
Hi, do you have experience with native Android ExoPlayer? If yes and you're free to take up a freelancing project, please let me know. I have sent you a connection request on LinkedIn. will discuss in detail.

**Comment by zezo357** [comment]
in 4.2.24
 you can add the overlay like this, will work on both fullscreen and normal mode
 
 ```
 MeeduVideoPlayer(
            controller: _meeduPlayerController,
            videoOverlay: (context, controller, responsive) => Container(
              color: Colors.red,
              child: SizedBox(
                height: 50,
                width: 50,
              ),
            ),
            header: (context, controller, responsive) => header,
          ),
 ```
