### ISSUE TITLE
In the debug console, the log shows an error, but the printed DataStatus is loading

### ISSUE THREAD

**Issue by ijuniorfu** [zezo357/flutter_meedu_videoplayer#161]
```shell
[log] {"timestamp":"2023-08-15T07:02:16.368963Z","level":"error","prefix":"cplayer","message":"Failed to recognize file format."}
```

**Comment by ijuniorfu** [comment]
In the debug console, the log shows an error, but the printed DataStatus is loading

**Comment by zezo357** [comment]
some of the logs are handled by media_kit, if playback is stopped then thats a playback error and should show on screen

also if initMeeduPlayer(throwErrors=false)

those errors will not get handled

**Comment by ijuniorfu** [comment]
What should I do to change the datastatus to error？

**Comment by zezo357** [comment]
Nothing, it should show the error by default, if you have an example I can test that will help greatly
