### ISSUE TITLE
mpv-dev-x86_64-20230811-git-140ec21.7z integrity check failed.

### ISSUE THREAD

**Issue by wxjrkm520** [zezo357/flutter_meedu_videoplayer#163]
mpv-dev-x86_64-20230811-git-140ec21.7z integrity check failed.

**Comment by wxjrkm520** [comment]
If two situations are encountered:

ANGLE.7z or mpv-dev-x86_64-20230811-git-140ec21.7z

Need to delete directory: build/windows/mpv-dev-x86_64-20230811-git-140ec21.7z or build/windows/ANGLE.7z

The reason for encountering these two problems may be due to exiting midway through the "flutter build windows"。

Because there may be files that were not downloaded during the process of cmake running and were closed, it is necessary to wait for cmake to download these two files before running. Otherwise, deleting them directly is the best solution。

**Comment by zezo357** [comment]
Yes this is done by media_kit and their fix if it happens flutter clean and try again

**Comment by wxjrkm520** [comment]
> 
If cmake exits midway, 'fluent clean' may not delete these two files because they are in a state occupied by cmake. In this case, it is necessary to kill the cmake process and clean it again to solve the problem

**Comment by zezo357** [comment]
> > 
> If cmake exits midway, 'fluent clean' may not delete these two files because they are in a state occupied by cmake. In this case, it is necessary to kill the cmake process and clean it again to solve the problem
> 
> 

Yeah that happened to me too, thank you for mentioning it and how to solve it, hopefully it helps another people too.
