### ISSUE TITLE
[Windows] mpv-dev-x86_64-20230807-git-140ec21.7z integrity check failed.

### ISSUE THREAD

**Issue by coder-xb** [zezo357/flutter_meedu_videoplayer#167]
As the title，I am developing a Windows desktop application with ``flutter_meedu_videoplayer: ^4.2.26``，but when run ``flutter run windows -d``，I have encountered the problem:
![WX20230821-153924@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/3dde11f4-77dd-4deb-9330-d9b3aa2e8ebd)
And，this my ``flutter doctor``:
![WX20230821-154150@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/122078d3-8f05-4989-a404-7171ea57e851)
In addition, I have tried the following command more than once, but the problem still exists:
``flutter clean``  ``flutter pub cache clean`` ``flutter pub get`` ``flutter pub upgrade``
And, there is a empty project for windwos desktop with ``flutter_meedu_videoplayer: ^4.2.26`` only，It also encounter this issue and cannot run properly:
[untitled.zip](https://github.com/zezo357/flutter_meedu_videoplayer/files/12393531/untitled.zip)
So, I need some helps!

**Comment by zezo357** [comment]
media_kit disabled all of my packages, so for now 

this is a work in progress, but i think it should work on all platforms only web is not supported for now 
```
  flutter_meedu_videoplayer:
    git:
      url: https://github.com/zezo357/flutter_meedu_videoplayer
      ref: fvp
      path: ./package
```

let me know if you have a problem with it, for now it will use fvp in all platforms

**Comment by coder-xb** [comment]
Thanks, I have tried with it, but I have encountered the problem: 
![WX20230821-170521@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/f78d8884-f6c4-46f3-b4e5-dcac29d0b52e)
Then, I close the player and opening it again is played.  That is to say, when using it to play videos, there is a gap between the above errors and the video screen appearing, that is: first play is error and then the second play video screen appearing, third is error and fourth is video screen appearing...And, the video screen may have a splash problem （The red line in the picture represents the overall area of the video）:
![WX20230821-170947@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/692c674f-d2ea-4f16-b82a-c82877060f31)

**Comment by coder-xb** [comment]
There is the screen recording for it:

https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/12847c56-1d9d-4b02-9f69-fc96003399c5

**Comment by zezo357** [comment]
> Thanks, I have tried with it, but I have encountered the problem: ![WX20230821-170521@2x](https://user-images.githubusercontent.com/34667902/261975547-f78d8884-f6c4-46f3-b4e5-dcac29d0b52e.png) Then, I close the player and opening it again is played. That is to say, when using it to play videos, there is a gap between the above errors and the video screen appearing, that is: first play is error and then the second play video screen appearing, third is error and fourth is video screen appearing...And, the video screen may have a splash problem （The red line in the picture represents the overall area of the video）: ![WX20230821-170947@2x](https://user-images.githubusercontent.com/34667902/261977352-692c674f-d2ea-4f16-b82a-c82877060f31.png)

sadly i cant check it right now, but i think it may be related to fvp i will check it before releasing the new version 

if you can provide the video you are testing with that will help greatly

**Comment by coder-xb** [comment]
Not just one video, all videos are like this:

https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/f1f26f67-783c-4e54-9206-7d47d2d51955

There is two videos, and the problem is the same.

**Comment by zezo357** [comment]
okay, will check it, thank you

**Comment by coder-xb** [comment]
But, I am waiting for the official version to be launched here. Is there any emergency solution or can the ``flutter_meedu_videoplayer`` previous version make the video play normally??

**Comment by zezo357** [comment]
sadly media_kit disables the app if the package is found 

but you can add 
in pubspec `video_player_win: ^2.2.2`
and
after initMeeduPlayer
```
import 'package:video_player_win/video_player_win_plugin.dart';

if (!kIsWeb && Platform.isWindows) WindowsVideoPlayer.registerWith();
```

this will use another logic to render the video, maybe its better in your case 

let me know if it works for you

**Comment by coder-xb** [comment]
Very unfortunate, I followed what you said add in pubspec ``video_player_win: ^2.2.2``, and after initMeeduPlayer 
```
import 'package:video_player_win/video_player_win_plugin.dart';
if (!kIsWeb && Platform.isWindows) WindowsVideoPlayer.registerWith();
```
It has encountered a new issue, causing the video to be unable to play and the screen to go blank:
![WX20230821-184148@2x](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/43e8c7a0-90d3-44c7-9758-edb3e748818a)
Additionally, I have also tried use ``video_player_win: ^ 2.2.2`` alone, The error content is consistent with the above

**Comment by zezo357** [comment]
well sadly you will have to wait for the release 

and for the problem with the render i opened an issue for it in fvp hopefully it gets fixed 
https://github.com/wang-bin/fvp/issues/11

if you cant wait then i will have to say use media_kit directly since they even broke the wrapper i implemented

**Comment by coder-xb** [comment]
Enn... I am planning to use ``media_kit`` and its related plugins directly to try

**Comment by annd22** [comment]
same issue

**Comment by coder-xb** [comment]
> > Enn... I am planning to use `media_kit` and its related plugins directly to try
> 
> i hope the best for you, and if you need any help let me know

Okay, Thank you

**Comment by zezo357** [comment]
> same issue

media_kit disabled all of my packages, so for now 

this is a work in progress, but i think it should work on all platforms only web is not supported for now 
```
  flutter_meedu_videoplayer:
    git:
      url: https://github.com/zezo357/flutter_meedu_videoplayer
      ref: fvp
      path: ./package
```

let me know if you have a problem with it, for now it will use fvp in all platforms 

and if that didnt work for your case sadly you will have to use media_kit directly or wait until i make a new release where i was able to fix the issues in the current logic

**Comment by annd22** [comment]
I tried and it cannot find the `Player` from `package:flutter_meedu_videoplayer/meedu_player.dart`

**Comment by zezo357** [comment]
what do you mean by player?

**Comment by zezo357** [comment]
meedu_player doesnt have a "player" class 

do you mean the media_kit one? if thats the case you will need to fully convert your code to use media_kit you cant import this package with media_kit (media_kit will close the app on launch)

**Comment by annd22** [comment]
oh, thank you, I will find another solution.

**Comment by annd22** [comment]
but can I have a final confirm.
- now `flutter_meedu_videoplayer` is not related to `media_kit` (and in the furure)?
- these 2 lib cannot be used in 1 project?
- is this effect on all platform?
- is there anyway that I can use an old version for now, which not have errors (maybe some dependencies override)?

**Comment by zezo357** [comment]
> but can I have a final confirm.
> 
* now `flutter_meedu_videoplayer` is not related to `media_kit` (and in the furure)? yes 
* these 2 lib cannot be used in 1 project? yes
 * is this effect on all platform? macos and ios work for now , but most probably wont on the long run
* is there anyway that I can use an old version for now, which not have errors (maybe some dependencies override)? No, media_kit deleted all old versions to break any workaround using old versions

**Comment by zezo357** [comment]
> Not just one video, all videos are like this:
> 
>  2023-08-21.17.28.45.mov 
> There is two videos, and the problem is the same.

for this can you provide the logs ?
```
Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((record) {
    print('${record.loggerName}.${record.level.name}: ${record.time}: ${record.message}');
  });
  ```
  
  it will help us greatly

**Comment by AnonymHK** [comment]
> > same issue
> 
> media_kit disabled all of my packages, so for now
> 
> this is a work in progress, but i think it should work on all platforms only web is not supported for now
> 
> ```
>   flutter_meedu_videoplayer:
>     git:
>       url: https://github.com/zezo357/flutter_meedu_videoplayer
>       ref: fvp
>       path: ./package
> ```
> 
> let me know if you have a problem with it, for now it will use fvp in all platforms
> 
> and if that didnt work for your case sadly you will have to use media_kit directly or wait until i make a new release where i was able to fix the issues in the current logic

 Can you confirm that the new version using fvp does not support web? If the new version does not support the web, I will have to give up "flutter_meedu_videoplayer" and look for a solution again!

**Comment by AnonymHK** [comment]
Looking forward to your new version being released, I have been waiting for 12 hours in the discussion area because the old version is also unusable and I have to stop working!

**Comment by zezo357** [comment]
>  Looking forward to your new version being released, I have been waiting for 12 hours in the discussion area because the old version is also unusable and I have to stop working! 

Remind me did you try the fvp version I mentioned? Can you let me know what didnt work for you?

**Comment by AnonymHK** [comment]
I have tried... Unfortunately, I am not sure where the problem occurred. I cleaned the project and even reinstalled NDK, but the compilation still went wrong! The error prompt did not find the file, but I don't know how to solve it! 

* What went wrong:
Execution failed for task ':fvp:configureCMakeDebug'.
> C/C++: C:\Pub\Cache\hosted\pub.flutter-io.cn\fvp-0.1.0\android\CMakeLists.txt debug|armeabi-v7a : CMake Error at C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fvp-0.1.0\android\CMakeLists.txt:67 (include):
    include could not find load file:

      mdk-sdk/lib/cmake/FindMDK.cmake

**Comment by zezo357** [comment]
> I have tried... Unfortunately, I am not sure where the problem occurred. I cleaned the project and even reinstalled NDK, but the compilation still went wrong! The error prompt did not find the file, but I don't know how to solve it!
> 
> * What went wrong:
>   Execution failed for task ':fvp:configureCMakeDebug'.
> 
> > C/C++: C:\Pub\Cache\hosted\pub.flutter-io.cn\fvp-0.1.0\android\CMakeLists.txt debug|armeabi-v7a : CMake Error at C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\fvp-0.1.0\android\CMakeLists.txt:67 (include):
> > include could not find load file:
> 
> ```
>   mdk-sdk/lib/cmake/FindMDK.cmake
> ```

yes i got it i just opened pr in fvp for a similar error

**Comment by zezo357** [comment]
please check new release

**Comment by coder-xb** [comment]
Okay，There is the logs of ``Exception: No Stream<VideoEvent> for textureId: -1``:
![exception](https://github.com/zezo357/flutter_meedu_videoplayer/assets/34667902/dce8717d-aed8-48be-9c13-e09b307647e4)
And，This is the logs of ``video can be played, but the screen is splash``:
[splash_screen.txt](https://github.com/zezo357/flutter_meedu_videoplayer/files/12404065/splash_screen.txt)

**Comment by coder-xb** [comment]
> Okay，There is the logs of `Exception: No Stream<VideoEvent> for textureId: -1`: ![exception](https://user-images.githubusercontent.com/34667902/262202226-dce8717d-aed8-48be-9c13-e09b307647e4.png) And，This is the logs of `video can be played, but the screen is splash`: [splash_screen.txt](https://github.com/zezo357/flutter_meedu_videoplayer/files/12404065/splash_screen.txt)

In the ``splash_screen.txt``，I have made desensitization modifications to some path data

**Comment by zezo357** [comment]
@coder-xb  this is on the latest version?

**Comment by coder-xb** [comment]
@zezo357 Yes, This is ``flutter_meedu_videoplayer`` fvp branch

**Comment by zezo357** [comment]
> @zezo357 Yes, This is `flutter_meedu_videoplayer` fvp branch

can you try on the release too?

**Comment by coder-xb** [comment]
> > @zezo357 Yes, This is `flutter_meedu_videoplayer` fvp branch
> 
> can you try on the release too?

Not yet. Currently, for emergency purposes, I am using media_kit directly.

**Comment by zezo357** [comment]
> > > @zezo357 Yes, This is `flutter_meedu_videoplayer` fvp branch
> > 
> > 
> > can you try on the release too?
> 
> Not yet. Currently, for emergency purposes, I am using media_kit directly.

its okay, thank you very much.

**Comment by coder-xb** [comment]
Have you released the new version?

**Comment by zezo357** [comment]
> Have you released the new version?

Yes I did yesterday

**Comment by zezo357** [comment]
4.3.0

**Comment by coder-xb** [comment]
Okay, I will try and test it in future versions of my application.

**Comment by zezo357** [comment]
> Okay, I will try and test it in future versions of my application.

If you did the migration, then I recommend you stick with it, since not all bugs or issues has been fixed yet, 

It's working very good on Android/iOS/web/macos 

Windows and Linux are not tested to make sure everything is good yet, it should work correctly but no promises here 😢

If you left the branch of using my package, then all is good try and let me know if you have any issues and I will try my best to solve it

**Comment by coder-xb** [comment]
> > Okay, I will try and test it in future versions of my application.
> 
> If you did the migration, then I recommend you stick with it, since not all bugs or issues has been fixed yet,
> 
> It's working very good on Android/iOS/web/macos
> 
> Windows and Linux are not tested to make sure everything is good yet, it should work correctly but no promises here 😢
> 
> If you left the branch of using my package, then all is good try and let me know if you have any issues and I will try my best to solve it

Okay，Thank you

**Comment by annd22** [comment]
new release working on windows, but can I ask in future release, is there any change that I can use meedu with media_kit? (now Im using media_kit for audio player)

**Comment by zezo357** [comment]
> new release working on windows (if I remove the media_kit lib), but can I ask in future release, is there any change that I can use meedu with media_kit? (now Im using media_kit for audio player)

Sadly you would have to request that from media_kit since they are the ones who implemented the logic to terminate any connection between us and them
