### ISSUE TITLE
 Abnormal playback of the new fvp version m3u8 

### ISSUE THREAD

**Issue by AnonymHK** [zezo357/flutter_meedu_videoplayer#169]
[flutter_meedu_videoplayer] Exception: No Stream<VideoEvent> for textureId: -1.
[flutter_meedu_videoplayer] #0      MdkVideoPlayer.videoEventsFor (package:fvp/src/video_player_mdk.dart:207:5)
#1      VideoPlayerController.initialize (package:video_player/video_player.dart:488:10)
<asynchronous suspension>
#2      MeeduPlayerController.setDataSource (package:flutter_meedu_videoplayer/src/controller.dart:533:7)
<asynchronous suspension>
#3      _M3u8ExamplePageState._setDataSource (package:flutter_meedu_videoplayer_example/pages/m3u8_page_example.dart:285:7)
<asynchronous suspension>

 There is another issue, I am not sure if it is a problem with fvp. If the network is disconnected and restored, the buffered video will not continue to play!

**Comment by zezo357** [comment]
I think it's related to fvp, yes it's from it's logic 

Also on what platform?

**Comment by AnonymHK** [comment]
Playing on the web is normal, but this error occurred on Android!

**Comment by zezo357** [comment]
Just disable fvp on Android from the initmeedu

It will work using official video_player

**Comment by AnonymHK** [comment]
If there is a problem with even such a basic playback format, I am very concerned about the robustness of the fvp library!

**Comment by AnonymHK** [comment]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/110597435/318262ec-7040-474e-9704-3f5b71681ec0)
 Is fvp not used by default?

**Comment by zezo357** [comment]
Yes it's not used by default, but on the example I think I left it enabled

**Comment by zezo357** [comment]
>  If there is a problem with even such a basic playback format, I am very concerned about the robustness of the fvp library! 

I tested it using macos, and it was working very good, 

Also it's in early stages so bugs are logical to occur, right now the only problem if windows or Linux has bugs those will be a problem

**Comment by AnonymHK** [comment]
> I think it's related to fvp, yes it's from it's logic
> 
> Also on what platform?
> 
> I would love if you can open an issue for fvp explaining the steps to reproduce it
> 
> Just to help the package maintainer fix and improve the package


 I am running M3u8ExamplePage in the example. You can try running it on an emulator or Android phone, and an error will be reported directly!

**Comment by AnonymHK** [comment]
Yes, after disabling, the playback of the m3u8 sample is normal!

**Comment by zezo357** [comment]
opened an issue
https://github.com/wang-bin/fvp/issues/15

**Comment by AnonymHK** [comment]
Thank you very much, you are still dealing with the problem so late!

**Comment by zezo357** [comment]
> Thank you very much, you are still dealing with the problem so late!

i had to suffer today to avoid making people suffer 

hopefully we get the package back to working state

thank you for keeping up with me and helping when you had stuff to do <3

**Comment by AnonymHK** [comment]
I really like flutter_meedu_videoplayer and I look forward to more people using it! I hope it becomes more and more stable!

**Comment by AnonymHK** [comment]
I see that the author of Fvp has released a new version that solves playback issues in Windows and M3U8. Please update our version dependency!

**Comment by zezo357** [comment]
> I saw that the author of Fvp has released a new version that addresses playback issues in Windows and M3U8. Please update our version dependencies after testing!

they didnt release yet

**Comment by zezo357** [comment]
they published, flutter upgrade should be enough

**Comment by AnonymHK** [comment]
Okay, waiting for your testing and updates!

**Comment by zezo357** [comment]
> Okay, waiting for your testing and updates!

i tested it on fvp it was working correctly, so everything should be good, let me know if there is another problem

**Comment by AnonymHK** [comment]
I just tested the new version, but unfortunately, I still cannot compile it! 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fvp:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using C:\Users\Pub\Cache\hosted\pub.flutter-io.cn\fvp-0.2.1\android\CMakeLists.txt: -- android-16 is not supported for arm64-v8a. Using minimum supported LP64 version 21.
  -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The CXX compiler identification is Clang 12.0.8

CMake Error at CMakeLists.txt:67 (include):
    include could not find requested file:

      C:/Users/Pub/Cache/hosted/pub.flutter-io.cn/fvp-0.2.1/android/mdk-sdk/lib/cmake/FindMDK.cmake

**Comment by AnonymHK** [comment]
I have upgraded to 7.4.2 for Gradle ！

**Comment by zezo357** [comment]
can you do flutter clean and try again, i think the code failed to download the file, since i just tested and it works

**Comment by AnonymHK** [comment]
Flutter clean I have tried! Invalid, I checked the error message and found that the file FindMDK.cmake is not available in the directory fvp-0.2.1! 

Cache/hosted/pub.flutter-io.cn/fvp-0.2.1/android/mdk-sdk/lib/cmake/FindMDK.cmake

android/mdk-sdk/    The directory 'mdk sdk/' does not exist

**Comment by AnonymHK** [comment]
I found the reason, https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-android.7z Not a valid download address, it's just a download page!

**Comment by zezo357** [comment]
> 

it does download for me

let me do a flutter clean and try again

**Comment by AnonymHK** [comment]
The actual download address is https://altushost-swe.dl.sourceforge.net/project/mdk-sdk/nightly/mdk-sdk-android.7z I have submitted an issue to the author for correction!
