### ISSUE TITLE
About Full Screen Playback

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#174]
![IMG_20230905_213153.jpg](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/70838b7b-370c-470b-ad26-f1f7099f35bd)

Full screen, I noticed that there would be a black border in a safe area, which should not actually exist. The image should cover the entire screen. I tried to modify it directly in the fullplaypage, but it didn't work. Does anyone know how to completely cover the screen.The screen is fully covered without black borders.

**Comment by zezo357** [comment]
Check this https://stackoverflow.com/questions/54408383/flutter-notch-area-is-blank-when-status-bar-is-disabled
