### ISSUE TITLE
Package Status

### ISSUE THREAD

**Issue by OmarYehiaDev** [zezo357/flutter_meedu_videoplayer#187]
Hello @abdelaziz-mahdy 

I'm working with ur package in some kind of a mega project and I noticed that u marked it as a discontinued. So i was trying to find replacements for it. BUT I didn't find any replacement for it. I noticed that it's now being updated so r u working on it again so i can use it or what? I need ur information ASAP really :""

**Comment by abdelaziz-mahdy** [comment]
I don't plan to add nor remove any features, I just fixed the package for people that was using it to avoid problems for people,


I made another package for controls which is way more cleaner 

You can migrate to it https://pub.dev/packages/universal_video_controls

**Comment by OmarYehiaDev** [comment]
> I don't plan to add nor remove any features, I just fixed the package for people that was using it to avoid problems for people,
> 
> I made another package for controls which is way more cleaner
> 
> You can migrate to it https://pub.dev/packages/universal_video_controls

Okay, that's cool. I'll check it and migrate to it ASAP :")
Thank you❤️️
