### ISSUE TITLE
Adding package breaks project

### ISSUE THREAD

**Issue by ollydixon** [zezo357/flutter_meedu_videoplayer#2]
After adding the package to dependencies like so: 

`flutter_meedu_videoplayer: ^1.0.1 `

We get the errors:
![Screenshot 2022-06-11 124013](https://user-images.githubusercontent.com/6940726/173184386-997958f5-44c7-4898-88f1-43b82fcde10f.png)

**Comment by ollydixon** [comment]
Using `meedu_player: ^0.5.0-nullsafety.0` also produces a lot of errors.

**Comment by zezo357** [comment]
will try to find the cause of the errors

**Comment by zezo357** [comment]
@ollydixon from what I am seeing you are trying to build for web right?

**Comment by ollydixon** [comment]
@zezo357 no windows :-)

**Comment by zezo357** [comment]
> @zezo357 no windows :-)

okay 

give me a minute to check where is the problem

also, can you provide the error log?

**Comment by zezo357** [comment]
@ollydixon can you check again after the update
and send error logs if the problem persists
