### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by srinivascse** [zezo357/flutter_meedu_videoplayer#22]
unable to fit the size of the video. if we are using grdiview

**Comment by zezo357** [comment]
Can you provide an example code with an issue to try to fix it 


Also on what platform are you having this issue

**Comment by srinivascse** [comment]
i try to show the video in a grid with crossaxis count 3 in windows.if the crossaxis count is 2 it will accept
if it is 3 it wont accept

**Comment by srinivascse** [comment]
GridView.builder(
            gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                maxCrossAxisExtent: 450,
                childAspectRatio: 16 / 9,
                crossAxisSpacing: 0,
                mainAxisSpacing: 0),
            itemCount: videos.length,
            itemBuilder: (BuildContext ctx, index) {
              return videos[index].type == 2
                  ? Card(
                semanticContainer: true,
                clipBehavior: Clip.antiAliasWithSaveLayer,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
                elevation: 5,
                child: Image.network(
                  videos[index].url,
                  fit: BoxFit.fill,
                  loadingBuilder: (BuildContext context, Widget child,
                      ImageChunkEvent? loadingProgress) {
                    if (loadingProgress == null) return child;
                    return Center(
                      child: CircularProgressIndicator(
                        value: loadingProgress.expectedTotalBytes !=
                            null
                            ? loadingProgress.cumulativeBytesLoaded /
                            loadingProgress.expectedTotalBytes!
                            : null,
                      ),
                    );
                  },
                ),
              )
                  : Card(
                semanticContainer: true,
                clipBehavior: Clip.antiAliasWithSaveLayer,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
                elevation: 5,
                child: MeeduVideoPlayer(
                  controller: myProducts[index],
                ),
              );
            })

**Comment by zezo357** [comment]
> i try to show the video in a grid with crossaxis count 3 in windows.if the crossaxis count is 2 it will accept
> if it is 3 it wont accept
> 

What do you mean won't accept


I will try to test it later

**Comment by srinivascse** [comment]
unable to fit the width of the video player..

**Comment by srinivascse** [comment]
SizedBox(
          height: MediaQuery.of(context).size.height* 0.10,
          width: MediaQuery.of(context).size.width* 0.30,
          child: MeeduVideoPlayer(
            controller: _meeduPlayerController,

          ),
        ),
unable to control the width .
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

**Comment by zezo357** [comment]
@srinivascse Fixed in 3.0.2
