### ISSUE TITLE
Video Quality button for .m3u8 

### ISSUE THREAD

**Issue by armanhadifatah** [zezo357/flutter_meedu_videoplayer#23]
Could it be possible to add a button for changing the quality of the video if the link was hls

**Comment by zezo357** [comment]
It will require some loading time, but I will try to do it

**Comment by zezo357** [comment]
It will require some loading time, but I will try to do it 


Btw you can do it on your own by providing the qualities like the example

**Comment by zezo357** [comment]
I apologize for the delay, but I have added an example of parsing code for m3u8 to my GitHub repository. You can find it here: https://github.com/zezo357/flutter_meedu_videoplayer/blob/master/package/example/lib/pages/m3u8_page_example.dart

the demo app which showcases the capabilities of the code. You can access it here: (m3u8 doesnt work on web)
https://zezo357.github.io/flutter_meedu_videoplayer_example/

Please let me know if you have any further questions or concerns.
