### ISSUE TITLE
linux some file are missing in linux please add as soon as possible

### ISSUE THREAD

**Issue by secanonm** [zezo357/flutter_meedu_videoplayer#24]
"flutter/ephemeral/.plugin_symlinks/flutter_meedu_videoplayer/linux" which
  is not an existing directory.

**Comment by zezo357** [comment]
Will check what causes the error and try to fix it

**Comment by secanonm** [comment]
i fixed it... 
if you wanna fixed it just enable linux support or add my pull request 

Thank You

**Comment by secanonm** [comment]
https://github.com/secanonm/flutter_meedu_videoplayer

here is it

**Comment by secanonm** [comment]
done brother

**Comment by zezo357** [comment]
@secanonm merged
