### ISSUE TITLE
Plugin huge size

### ISSUE THREAD

**Issue by asmith20002** [zezo357/flutter_meedu_videoplayer#30]
Hello,

Testing on Windows 11. Flutter 3.3.10.
I've just built a release mode with **raw flutter** app. 

`flutter build windows --release`

 pubspec only:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_meedu_videoplayer: ^3.0.3
```

The size of the plugins is over 120MB!! Are you aware of that?

![meedu](https://user-images.githubusercontent.com/17809451/213859938-6d50e0d2-de7d-421e-8e99-bfd3cc982aef.png)

### Flutter doctor:
```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

**Comment by zezo357** [comment]
Yes this is due to VLC being included in windows builds by the package dart_vlc.



For the future I think I will convert to using media_kit by the same developer when it's published since I should deliver better performance and better video playback.


For now this is the only working solution, I found

**Comment by zezo357** [comment]
using media_kit should make bundle size smaller and video player faster.
