### ISSUE TITLE
Video crashing on linux, only audio is playing

### ISSUE THREAD

**Issue by singwithaashish** [zezo357/flutter_meedu_videoplayer#31]
Hello, I am getting this error

`2
flutter: Fit is BoxFit.fill
[00007fe9a803a840] prefetch stream error: cannot seek (to offset 20576829)
[h264 @ 0x7fe9a8332b00] Invalid NAL unit size (1670 > 709).
[h264 @ 0x7fe9a8332b00] Error splitting the input into NAL units.
flutter: Duration is 0:00:30.030000`

this is where im being sent as soon as the app launches:
![image](https://user-images.githubusercontent.com/52033403/213868624-4afb1865-d305-4fcc-9315-38dbf56c1993.png)
![image](https://user-images.githubusercontent.com/52033403/213868638-793d4dd6-241e-4e35-835d-91008c3f2e09.png)

I am using the code and the video link from the quick start page

Also, there is no documentation to implement custom icons and to remove the default overlays on the video,

**Comment by zezo357** [comment]
There is a documentation link at the end of the documentation


Also I don't know what is causing the problem in Linux since I don't use it @secanonm can you help?

**Comment by secanonm** [comment]
Please provide more details ( logs )
Or few commands output

1. Flutter doctor -v 
2. name -a 
Please also mention video link 


Error occurs in Wakelock package in future we will fixed out 

Thank you ☺️

**Comment by singwithaashish** [comment]
Thank you guys for your response. 
here's flutter doctor -v :
`[✓] Flutter (Channel stable, 3.3.10, on Linux Mint 20.3 5.4.0-137-generic,
    locale en_IN)
    • Flutter version 3.3.10 on channel stable at
      /home/beautiful/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/beautiful/Android/Sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /home/beautiful/Templates/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/beautiful/Templates/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.3
      5.4.0-137-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

and here's uname -a: 
`Linux beautiful-Aspire-E5-573 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
video link : https://movietrailers.apple.com/movies/paramount/the-spongebob-movie-sponge-on-the-run/the-spongebob-movie-sponge-on-the-run-big-game_h720p.mov
Thanks again for your help.

**Comment by secanonm** [comment]
Every thing is great brother but install flutter without using snap 

Because snap and apt are different package manager you need to install vlc and libvlc package

So install flutter manually or using git stable

Thank you ☺️

**Comment by PureTryOut** [comment]
I have Flutter installed manually (without Snap) and have VLC installed through my package manager (Arch Linux) and still have the same problem. Although in my case it doesn't even play the audio and errors out immediately in the WakeLockApi.

**Comment by zezo357** [comment]
Mybad wake lock has no support for Linux I will make an update disabling it for Linux 


If someone knows a wakelock alternative for Linux let me know to use it

**Comment by zezo357** [comment]
@PureTryOut @singwithaashish fixed in 3.0.5, can you test it?

**Comment by singwithaashish** [comment]
Thank you, I'll test it and let you know.

**Comment by zezo357** [comment]
I wanted to let you know that we will be closing this issue as we have not received a response. However, if you have any further questions or concerns, please do not hesitate to reach out to me. I am here to assist you in any way I can.
