### ISSUE TITLE
Problem when trying to run video on windows

### ISSUE THREAD

**Issue by Mopilani** [zezo357/flutter_meedu_videoplayer#35]
flutter: {connectionId: 3, n: 0, syncMillis: 0, writtenTo: null, writeConcern: {w: 1, wtimeout: 0}, err: null, ok: 1.0}
flutter: {connectionId: 3, n: 0, syncMillis: 0, writtenTo: null, writeConcern: {w: 1, wtimeout: 0}, err: null, ok: 1.0}
flutter: true
flutter: Fit is BoxFit.fill
flutter: Null check operator used on a null value
flutter: #0      MeeduPlayerController._createVideoController
#1      MeeduPlayerController.setDataSource
#2      _BasicPlayerState._init
#3      _BasicPlayerState.initState.<anonymous closure>
#4      SchedulerBinding._invokeFrameCallback
#5      SchedulerBinding.handleDrawFrame
#6      SchedulerBinding._handleDrawFrame
#7      _invoke (dart:ui/hooks.dart:145:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#9      _drawFrame (dart:ui/hooks.dart:112:31)
flutter: Last fit used was scaleDown
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      MeeduPlayerController.setDataSource
#1      _BasicPlayerState._init
#2      _BasicPlayerState.initState.<anonymous closure>
#3      SchedulerBinding._invokeFrameCallback
#4      SchedulerBinding.handleDrawFrame
#5      SchedulerBinding._handleDrawFrame
#6      _invoke (dart:ui/hooks.dart:145:13)
#7      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#8      _drawFrame (dart:ui/hooks.dart:112:31)
flutter: Fit is BoxFit.scaleDown

The lines above is the stacktrace when the error was throwen,
And this is flutter doctor -v output

[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.19041.1415], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (7 weeks ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Mopilani\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\Mopilani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

In my case i tryed to run mp4 and mkv videos and i am using a code from the example that were provided with the package.

**Comment by zezo357** [comment]
@Mopilani I see that you closed the issue, does that mean it it resolved?
