### ISSUE TITLE
Playing Youtube Live Streams

### ISSUE THREAD

**Issue by abhilashsajeev** [zezo357/flutter_meedu_videoplayer#47]
I successfully played a YouTube video by extracting the source URL, but I encountered an issue when attempting to play a live stream using the same method. Can you provide more information on how to utilize the plugin to play YouTube live streams?

**Comment by zezo357** [comment]
What are YouTube streams type,


 if bytes don't know if its possible


M3u8 should work.


Do you have any example using another package?

**Comment by abhilashsajeev** [comment]
@zezo357 There is https://pub.dev/packages/youtube_player_iframe. But it supports only Android , ios and web only.
Can u update the code such that giving direct youtube link will also play the video.

**Comment by zezo357** [comment]
@abhilashsajeev will check on it, and let you know what can be done.

**Comment by zezo357** [comment]
> @zezo357 There is https://pub.dev/packages/youtube_player_iframe. But it supports only Android , ios and web only. Can u update the code such that giving direct youtube link will also play the video.

from my understanding this package makes a webview and plays the video in it, which is very different from my package here we run the player directly in flutter this is much faster.

they are able to access stream because they play it like a browser.

`I successfully played a YouTube video by extracting the source URL,`

what is the problem in doing that?

**Comment by abhilashsajeev** [comment]
@zezo357 It would be great if your package could also support playing live streams from youtube or any such platforms

**Comment by zezo357** [comment]
> @zezo357 It would be great if your package could also support playing live streams from youtube or any such platforms

I don't understand, how they work and that will make the package very complex.


But I will keep in mind if I find a way to implement it I will let you know

**Comment by abhilashsajeev** [comment]
@zezo357 I think youtube live is hls live streams

**Comment by zezo357** [comment]
> @zezo357 I think youtube live is hls live streams

Yes I found that too, and this package can use it,

If you are able to get the url for the other videos too they can play correctly.

**Comment by zezo357** [comment]
in 4.0.10,I added example for playing from youtube.

**Comment by abhilashsajeev** [comment]
@zezo357 The youtube example working for normal videos only.vBut live streams still not supported

I have tried with this [url](https://www.youtube.com/watch?v=f-heZqb4eC8)

**Comment by zezo357** [comment]
> @zezo357 The youtube example working for normal videos only.vBut live streams still not supported
> 
> I have tried with this [url](https://www.youtube.com/watch?v=f-heZqb4eC8)

Ok will try to add live streams support

**Comment by zezo357** [comment]
> > @zezo357 The youtube example working for normal videos only.vBut live streams still not supported
> > I have tried with this [url](https://www.youtube.com/watch?v=f-heZqb4eC8)
> 
> Ok will try to add live streams support

![image](https://user-images.githubusercontent.com/25157308/230745966-e019b299-820a-4997-b605-47e5b9c884cc.png)
 this url works ?

**Comment by zezo357** [comment]
live streams now work, but since i am using video_player and it doesnt update duration i had to use inilize 

so `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed` will be spammed in the console 


the fix for this will be to switch fully to media_kit and drop video_player, this will happed when web support works in media_kit

**Comment by abhilashsajeev** [comment]
@zezo357 has this been udpated to the example page?

**Comment by zezo357** [comment]
> @zezo357 has this been udpated to the example page?

Yes. On GitHub, the same page updated to read live streams
