### ISSUE TITLE
web return from fullscreen throws error 

### ISSUE THREAD

**Issue by zezo357** [zezo357/flutter_meedu_videoplayer#51]
web return from fullscreen throws error and results in a black video player

**Comment by zezo357** [comment]
error fixed, but when going back from full screen the video_player is dark, guess its a video_player bug

**Comment by sanjayajena37** [comment]
Facing same error

**Comment by sanjayajena37** [comment]
Please resolve it

**Comment by zezo357** [comment]
I am trying to do it, and I figured out a fix but it didn't work 😢
,So I will try again since you guys has the same problem

**Comment by sanjayajena37** [comment]
Hi @zezo357. Thanks for your response. Am waiting for your resolution. 

Suggestion: if possible try to implement multiple audio track in this player. 

Like English, Hindi etc.

**Comment by zezo357** [comment]
> Hi @zezo357. Thanks for your response. Am waiting for your resolution. 
> 
> Suggestion: if possible try to implement multiple audio track in this player. 
> 
> Like English, Hindi etc.

Sadly, video_player doesn't support that, meanwhile media_kit does 

You can use my flutter_meedu_media_kit and use media_kit functions, if you don't need my controls you can use media_kit directly they have controls too.

**Comment by zezo357** [comment]
`4.2.16` fixes the web black screen.

**Comment by sanjayajena37** [comment]
Thanks buddy😇
