### ISSUE TITLE
Is there a way I can create a new one instead of the video control panel provided by flutter_meedu_videoplayer?

### ISSUE THREAD

**Issue by Bullets-jyr** [zezo357/flutter_meedu_videoplayer#53]
Is there a way I can create a new one instead of the video control panel provided by flutter_meedu_videoplayer? Because I have to apply a different UI than the video controll panel provided by flutter_meedu_videoplayer.

**Comment by zezo357** [comment]
may i ask you, what are the customization you require so i try to update the code if its not already customizable.

**Comment by zezo357** [comment]
@Bullets-jyr check version 4.1.0 
and this the demo for it
https://zezo357.github.io/flutter_meedu_videoplayer_example/#custom_controls
for code example check this 
https://github.com/zezo357/flutter_meedu_videoplayer/blob/master/package/example/lib/pages/custom_controls.dart
