### ISSUE TITLE
flutter_meedu_videoplayer video control pannel

### ISSUE THREAD

**Issue by Bullets-jyr** [zezo357/flutter_meedu_videoplayer#55]
In the control panel shown in the flutter_meedu_videoplayer library, I want to add a playback progress bar, back, forward, volume control, and other icons on the control panel to adjust the position and add other functions, but it doesn't seem to be that part. Can I create my own control panel using flutter's stack widget without using your control panel?

**Comment by zezo357** [comment]
check version 4.1.0
and this the demo for it
https://zezo357.github.io/flutter_meedu_videoplayer_example/#custom_controls
for code example check this
https://github.com/zezo357/flutter_meedu_videoplayer/blob/master/package/example/lib/pages/custom_controls.dart

**Comment by zezo357** [comment]
if you need any help open a issue with it.

and if that fixes your problem let me know to close this issue.

**Comment by zezo357** [comment]
also if you want me to implemnt the controls let know how they should look and i will do my best

**Comment by Bullets-jyr** [comment]
Discord invite code. Can we talk to each other here?
https://discord.gg/nhpDWWh3
