### ISSUE TITLE
can't build: can't be assigned to the parameter type

### ISSUE THREAD

**Issue by phamtuanduong** [zezo357/flutter_meedu_videoplayer#58]
Hello dear
![image](https://user-images.githubusercontent.com/17924277/232823713-ee5b52fb-8f1d-4bce-aa35-652c378126dd.png)

After I update the package, I can't build my program anymore, can you give me a way to fix it?

**Comment by zezo357** [comment]
A new version of media_kit is the reason of this 


You can use 

```
dependency_overrides:
  media_kit_video: 0.0.4
```

For a temporary fix, and will update the package tonight to fix that issue



Sorry for inconveniences.

**Comment by zezo357** [comment]
`flutter pub upgrade` will fix your issue

**Comment by phamtuanduong** [comment]
Have a nice day, thank you for your support
