### ISSUE TITLE
the player crashes on windows 11

### ISSUE THREAD

**Issue by moghoneim-code** [zezo357/flutter_meedu_videoplayer#6]
first i need to thank you for this great package 

but i have tried the app on 3 different devices that is using windows 11 and the app crashed as soon as i opened the player

**Comment by zezo357** [comment]
Can you please provide the error stack trace 



Also 99% it's related to vlc player but will make sure when I see the trace 😅

**Comment by moghoneim-code** [comment]
i've searched more and more , it doesn't happen many times , but it will always happen when the windows app is compressed into installer using apps such inno setup compiler .

**Comment by zezo357** [comment]
> i've searched more and more , it doesn't happen many times , but it will always happen when the windows app is compressed into installer using apps such inno setup compiler .

I can't help If I don't see the stack trace for the crash 🥲

**Comment by Qayoommaymon** [comment]
Hi @zezo357,
Thanks for sharing player implementation for windows. While using the player on windows app, the app window overflows when returning from the full screen (play mode) to previous screen size. Any help/suggestion will be highly appreciated. Thanks

**Comment by zezo357** [comment]
It's a problem related to window manger they fixed it in update but somehow it's back again, so I will check if can fix it
