### ISSUE TITLE
windows下报错了

### ISSUE THREAD

**Issue by guipie** [zezo357/flutter_meedu_videoplayer#70]
![1683730783610](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/3ba5a8c4-affd-4bf3-b6ee-62cd7a0a09db)

**Comment by zezo357** [comment]
Flutter clean and rerun

**Comment by guipie** [comment]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/acb8994f-7912-420f-b232-503fd1c9fc9a)

![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/a4d282e8-d959-4406-8e78-934f65838fc5)
获取的源码还是报错拉。

**Comment by zezo357** [comment]
I will check later, 

Can you provide flutter doctor output

**Comment by zezo357** [comment]
Can you redo flutter clean 


And flutter pub get 

And flutter run

**Comment by guipie** [comment]
Already implemented, still not working

**Comment by guipie** [comment]
![1683788335830](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/7320d257-199f-4706-9e81-8e59c381cbb0)
![1683788367643](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/3cc65706-9e1a-427b-9431-312a725378b7)
There is an error in this code, do you know what is the problem?

**Comment by zezo357** [comment]
Your downloads fail due to internet errors, all I can tell is you have to

Flutter clean and redownload until it downloads correctly

**Comment by guipie** [comment]
already executed Flutter clean and redownload。  Still getting an error like this

![1683793863596](https://github.com/zezo357/flutter_meedu_videoplayer/assets/55727172/f706a613-6879-406b-9a98-d5f5948b2b71)

**Comment by zezo357** [comment]
Can you check media_kit test code? If it's working or not?

**Comment by guipie** [comment]
You mean widget_test.dart in the test directory..  it's same error

**Comment by zezo357** [comment]
> You mean widget_test.dart in the test directory..  it's same error
> 
> 

I meant https://pub.dev/packages/media_kit since I use it for windows

**Comment by zezo357** [comment]
> ![1683788335830](https://user-images.githubusercontent.com/55727172/237599250-7320d257-199f-4706-9e81-8e59c381cbb0.png) ![1683788367643](https://user-images.githubusercontent.com/55727172/237599339-3cc65706-9e1a-427b-9431-312a725378b7.png) There is an error in this code, do you know what is the problem?

just to explain what is happening, this code in media_kit checks if the downloaded files are correct ,and it finds out they are not correct

so the build fails, and running flutter clean will delete it and when you rerun I will download again. 

(these problems happens mostly due to network errors)
