### ISSUE TITLE
Release build fails

### ISSUE THREAD

**Issue by mohamed-Etman** [zezo357/flutter_meedu_videoplayer#75]
```
Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (3 months ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1
```

Building the app in release mode apk or bundle fails with the this error

```
Dart snapshot generator failed with exit code -1073741819
Dart snapshot generator failed with exit code -1073741819
Dart snapshot generator failed with exit code -1073741819
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -1073741819
Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -1073741819
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -1073741819


FAILURE: Build failed with an exception.

* Where:

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

BUILD FAILED in 1m 55s
```

it only fails if i use the init function i have tracked the error down to the platform interface register function

```Dart
 static void registerWith({MPVLogLevel logLevel = MPVLogLevel.none}) {
    VideoPlayerPlatform.instance = VideoPlayerMediaKit();
 }
```

but it still fails even if i didnt use the media kit library just having the init function in main with both media kit libraries set to false still it fails

**Comment by zezo357** [comment]
Will try to build using flutter 3.7.1 and let you know, since it is working correctly on both 3.7.10 and 3.10

**Comment by mohamed-Etman** [comment]
I will update to 3.7.10 and try it and let you know

**Comment by zezo357** [comment]
https://github.com/zezo357/flutter_meedu_videoplayer/commit/6c5c8dd5574e3ddfde325725ae0692741782575a/checks?check_suite_id=12872391954


As you can see here it's a problem with 3.7.1

**Comment by mohamed-Etman** [comment]
I tested with 3.7.10 and it worked thank you for your help
