### ISSUE TITLE
Unable to compile after flutter upgrade (v3.10.0)

### ISSUE THREAD

**Issue by 0Franky** [zezo357/flutter_meedu_videoplayer#76]
Hi @zezo357 

Yesterday I upgraded my flutter version to 3.10.0.

I was trying to lunch your example code but I'm giving this errors:

`Launching lib\main.dart on Windows in debug mode...
main.dart:1
/C:/Users/-/AppData/Local/Pub/Cache/hosted/pub.dev/helpers-1.2.0/lib/helpers/misc.dart(127,7): error GBF4691A2: No named parameter with the name 'window'. [D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/-/AppData/Local/Pub/Cache/hosted/pub.dev/helpers-1.2.0/lib/helpers/misc_build/build_color.dart(33,42): error GD65BB2B6: The getter 'accentColor' isn't defined for the class 'ThemeData'. [D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/-/AppData/Local/Pub/Cache/hosted/pub.dev/helpers-1.2.0/lib/helpers/misc_build/build_color.dart(109,42): error GD65BB2B6: The getter 'buttonColor' isn't defined for the class 'ThemeData'. [D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: la compilazione personalizzata per 'D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\CMakeFiles\205649b68d02cc4897ce61264a7c9555\flutter_windows.dll.rule;D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\CMakeFiles\808581536beb0a9b893da9de0aa8029b\flutter_assemble.rule' � stata terminata. Codice: 1. [D:\Users\-\Desktop\flutter_meedu_videoplayer\package\example\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

This happens both on Windows and Linux.

This is my flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):

[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Versione 10.0.22621.1702], locale it-IT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.19)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.78.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!`

Can you help me?

**Comment by zezo357** [comment]
Do `flutter pub upgrade`
It should get fixed.

**Comment by zezo357** [comment]
to be safe use, `flutter_meedu_videoplayer: ^4.2.10`

**Comment by zezo357** [comment]
@0Franky is it safe to assume this is fixed?

**Comment by 0Franky** [comment]
Hi @zezo357,
I was busy with the PR code. 
I just checked and I was able to launch the app correctly after upgrading to 3.10
I think is fixed. 

Thank you again!
