### ISSUE TITLE
App freezes when used .m3u8 network url on windows 

### ISSUE THREAD

**Issue by Diya-Arif** [zezo357/flutter_meedu_videoplayer#77]
When trying to play a video in .m3u8 format, the application freezes even though the sound of the video is still playing

![Screenshot 2023-05-14 091400](https://github.com/zezo357/flutter_meedu_videoplayer/assets/133560359/d64b5041-4479-474b-bc73-2c20cef78a06)

**Comment by zezo357** [comment]
It's related to video_player interface


But this error can be ignored, since it's not valid 

Note: the pausing is caused because of vscode catching the exception

In release this will not get paused
