### ISSUE TITLE
Implementing Touch Lock Feature for the Flutter Meedu Video Player

### ISSUE THREAD

**Issue by SeongWoo-97** [zezo357/flutter_meedu_videoplayer#78]
I'm currently working on a project where I'm using your flutter_meedu_videoplayer package, and I've found it to be incredibly useful so far.

However, I've encountered a challenge. I'm trying to implement a touch lock feature to prevent unintended screen touches during video playback, but I couldn't find any method like 'controller.disable' in the package that could help me achieve this.

Could you provide me with some guidance on how I might implement such a feature? Any help or advice would be greatly appreciated.

Thank you so much for your work on the flutter_meedu_videoplayer package - it's been a great asset to my project.

**Comment by zezo357** [comment]
Will add it in next release, and most probably will add an example for it

**Comment by zezo357** [comment]
published in `4.2.11-dev`
