### ISSUE TITLE
on Windows and encountered initialization failure，Working normally on the move

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#83]
I used it on Windows and encountered initialization failure，Working normally on the move
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/53f965cd-3bf5-4510-a94b-b9198cea3c95)

there is code：

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late MeeduPlayerController _meeduPlayerController;

  @override
  void initState() {
    // TODO: implement initState
    _meeduPlayerController.setDataSource(
      DataSource(
        type: DataSourceType.network,
        source: "https://vip.lz-cdn14.com/20230411/21645_f68e95f2/index.m3u8",
      ),
      autoplay: true,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AspectRatio(
        aspectRatio: 16 / 9,
        child: MeeduVideoPlayer(controller: _meeduPlayerController),
      ),
    );
  }
}

**Comment by JieNengi** [comment]
`void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late MeeduPlayerController _meeduPlayerController;

  @override
  void initState() {
    // TODO: implement initState
    _meeduPlayerController.setDataSource(
      DataSource(
        type: DataSourceType.network,
        source: "https://vip.lz-cdn14.com/20230411/21645_f68e95f2/index.m3u8",
      ),
      autoplay: true,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AspectRatio(
        aspectRatio: 16 / 9,
        child: MeeduVideoPlayer(controller: _meeduPlayerController),
      ),
    );
  }
}
`

**Comment by JieNengi** [comment]
When I try this, I am prompted with a new error。
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/12b6760b-77c2-4ed4-ad73-b585d55e9ae0)
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/3e40672b-0849-4d5d-b55e-e72d1b1d3659)

**Comment by zezo357** [comment]
> I used it on Windows and encountered initialization failure，Working normally on the move
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/53f965cd-3bf5-4510-a94b-b9198cea3c95)
> 
> there is code：
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   const MyApp({super.key});
> 
>   @override
>   State<MyApp> createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Home(),
>     );
>   }
> }
> 
> class Home extends StatefulWidget {
>   const Home({super.key});
> 
>   @override
>   State<Home> createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
>   late MeeduPlayerController _meeduPlayerController;
> 
>   @override
>   void initState() {
>     // TODO: implement initState
>     _meeduPlayerController.setDataSource(
>       DataSource(
>         type: DataSourceType.network,
>         source: "https://vip.lz-cdn14.com/20230411/21645_f68e95f2/index.m3u8",
>       ),
>       autoplay: true,
>     );
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: AspectRatio(
>         aspectRatio: 16 / 9,
>         child: MeeduVideoPlayer(controller: _meeduPlayerController),
>       ),
>     );
>   }
> }
> 

For this you didn't add the controller
`late MeeduPlayerController _meeduPlayerController;`

**Comment by zezo357** [comment]
> When I try this, I am prompted with a new error。
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/12b6760b-77c2-4ed4-ad73-b585d55e9ae0)
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/3e40672b-0849-4d5d-b55e-e72d1b1d3659)
> 

Did you add this?

```
void main() {
  initMeeduPlayer(); //this line
  runApp(MyApp());
}
```

**Comment by JieNengi** [comment]
> > When I try this, I am prompted with a new error。
> > ![image](https://user-images.githubusercontent.com/42732005/238497866-12b6760b-77c2-4ed4-ad73-b585d55e9ae0.png)
> > ![image](https://user-images.githubusercontent.com/42732005/238497891-3e40672b-0849-4d5d-b55e-e72d1b1d3659.png)
> 
> Did you add this?
> 
> ```
> void main() {
>   initMeeduPlayer(); //this line
>   runApp(MyApp());
> }
> ```

Thanks, it solved my problem perfectly!
