### ISSUE TITLE
on windows, m3u8 link is always waiting to be played and loading

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#84]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/96dcf0fa-c373-4133-874d-cd4bcbf5f00b)
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/9fd188e6-d8cd-457e-83b8-ed6c6629724b)

**Comment by zezo357** [comment]
Hello, please test it on the example code, and if it works it a problem on your side



If it doesn't work, please provide the link so I can test and let you know

**Comment by JieNengi** [comment]
> 您好，请在示例代码上对其进行测试，如果它有效，则是您这边的问题
> 
> 如果它不起作用，请提供链接，以便我可以测试并通知您

you can use "https://vip.lz-cdn7.com/20230516/16027_b1c75bba/index.m3u8" to test,

**Comment by zezo357** [comment]
https://zezo357.github.io/flutter_meedu_videoplayer_example/#m3u8


It's working on this demo, can you try it on the package example code
