### ISSUE TITLE
onLongPressStart and onLongPressEnd

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#86]
go full screen,I need the relevant callback methods for onLongPressStart and onLongPressEnd, but I couldn't find.
Can we increase support?

**Comment by zezo357** [comment]
On video player long press? What is it for? And on desktop or mobile?


Did you try to wrap the video player with a gesture detector and implement those functions by yourself? (Note: I think the hit behavior should be translucent)

**Comment by JieNengi** [comment]
> On video player long press? What is it for? And on desktop or mobile?
> 
> Did you try to wrap the video player with a gesture detector and implement those functions by yourself? (Note: I think the hit behavior should be translucent)

on mobile，Users usually do this：
1.onLongPressStart：video will 2x speed play
2.onLongPressEnd：video returns to normal speed
I tried to use stack and add gesture to the topmost layer of flutter_meedu_videoplayer, but it didn't work.

**Comment by zezo357** [comment]
> 
> 
> 
> > On video player long press? What is it for? And on desktop or mobile?
> > 
> > Did you try to wrap the video player with a gesture detector and implement those functions by yourself? (Note: I think the hit behavior should be translucent)
> 
> on mobile，Users usually do this：
> 1.onLongPressStart：video will 2x speed play
> 2.onLongPressEnd：video returns to normal speed
> I tried to use stack and add gesture to the topmost layer of flutter_meedu_videoplayer, but it didn't work.
> 
> 

No need for stack just a gesture detector and the video player is the child

**Comment by JieNengi** [comment]
> > > On video player long press? What is it for? And on desktop or mobile?
> > > Did you try to wrap the video player with a gesture detector and implement those functions by yourself? (Note: I think the hit behavior should be translucent)
> > 
> > 
> > on mobile，Users usually do this：
> > 1.onLongPressStart：video will 2x speed play
> > 2.onLongPressEnd：video returns to normal speed
> > I tried to use stack and add gesture to the topmost layer of flutter_meedu_videoplayer, but it didn't work.
> 
> No need for stack just a gesture detector and the video player is the child

`AspectRatio(
                        aspectRatio: 16 / 9,
                        child: GestureDetector(
                          behavior: HitTestBehavior.opaque,
                          onLongPressStart: (details) {
                          },
                          onLongPressEnd: (details) {
                          },
                          child: MeeduVideoPlayer(
                            controller: _controller,
                          ),
                        ),
                      )`

The code is not valid when going to full screen playback.

**Comment by zezo357** [comment]
yes, okay i will add this to the main package and let you know how to enable it,

i think it should work on mobile, not desktop right?


most probably i will work on it tommorow

**Comment by JieNengi** [comment]
> 



> 

Yes, onLongPressStart and onLongPressEnd are very useful in mobile.
thanks！

**Comment by zezo357** [comment]
published in `4.2.11-dev`
