### ISSUE TITLE
[New feature] Appropriate caching 

### ISSUE THREAD

**Issue by AnonymHK** [zezo357/flutter_meedu_videoplayer#87]
I am using this component for teaching video production, mainly using Flutter to simulate a TikTok client. In actual teaching, I have used a large number of short videos and played them in a loop! The video will restart loading every time! Suggest adding an appropriate caching mechanism to improve the loading problem in Tiktok, a 15 to 30 second short video scenario!

**Comment by zezo357** [comment]
The caching is handled by media kit or video player 


So most probably I can't help with an example.

If you can provide an example code I will try to fix that issue
