### ISSUE TITLE
abort() has been callled

### ISSUE THREAD

**Issue by moghoneim-code** [zezo357/flutter_meedu_videoplayer#9]
hi , sorry to get back again with a new issue .. the problem this time when i create a project and add the package to it and run on windows it shows an error .. i have tried multiple solutions .. clear cache ..  change project .. change projects location .. clear cache of all flutter packages .. 

and even i upgraded the flutter version to the latest .. 

it says Debug Error 

abort() has been called 

![image](https://user-images.githubusercontent.com/72418844/192258717-aac7a97b-1484-4591-9123-ec412383e52c.png)

**Comment by zezo357** [comment]
Did you make the installation steps for dart vlc?

**Comment by moghoneim-code** [comment]
yes i did and i even copied the windows folder into my project but it didn't work .. note that i even reinstalled the c++ version in my device

**Comment by zezo357** [comment]
> yes i did and i even copied the windows folder into my project but it didn't work .. note that i even reinstalled the c++ version in my device

thats very weird, and you cant find any errors?

**Comment by moghoneim-code** [comment]
no errors in the console at all .. even i reinstalled android studio .. re run on vs code and still no solution

**Comment by zezo357** [comment]
> 

can you make a repo so i check your code?

**Comment by zezo357** [comment]
please mention me when you do it, and will check it ASAP

**Comment by moghoneim-code** [comment]
ok i will create an example

**Comment by UnluckyY1** [comment]
@zezo357 I am having the same issue on windows the moment I add flutter_meedu_videoplayer to my pubspec.yaml my app will crash immediately.

**Comment by zezo357** [comment]
Can you try to add dartvlc package? Maybe it's the problem

And follow the initializing steps


I don't have the problem so I don't know



Also are you using windows 11? Maybe it's related to it

**Comment by UnluckyY1** [comment]
> Can you try to add dartvlc package? Maybe it's the problem
> 
> And follow the initializing steps
> 
> I don't have the problem so I don't know
> 
> Also are you using windows 11? Maybe it's related to it

Yes, I am on Windows 11 but the example app works fine for me, I have tried to create a new flutter project with the last flutter version simply add `flutter_meedu_videoplayer`  to pubspec.yaml will ends up with the same crash.
i will check dartVLC and let you know

**Comment by zezo357** [comment]
Will check why it crashes, looks like a missed step in the setup and didn't add it to my read me

**Comment by UnluckyY1** [comment]
> Will check why it crashes, looks like a missed step in the setup, and didn't add it to my read me

well, I made a look at your work and I couldn't see any reason to publish the project as a Plugin (maybe I am missing something) instade I believe re_publishing the project as a package will solve the issue.

**Comment by zezo357** [comment]
The original code was a plugin so I didn't need to change it , also it works on windows 10 so I think there is something missing that crashes on windows 11

**Comment by UnluckyY1** [comment]
After a long investigation, it turns out that the crash was caused by `'auto_orientation: ^2.2.1'` for some reason that I don't know yet!

**Comment by zezo357** [comment]
> After a long investigation, it turns out that the crash was caused by `screen_brightness` for some reason that I don't know yet!

just tested new project  with the package and didnt crash 

can you make a repo for the  one that crashes?

**Comment by UnluckyY1** [comment]
I just tested on windows 10 and I had no crash, I can confirm that the crash will happen only with windows 11 also removing
the brightness feature and screen_brightness plugin will solve the problem for windows 11 I didn't find why the example app works fine on windows 11

**Comment by zezo357** [comment]
Maybe the main cpp file is different?

**Comment by moghoneim-code** [comment]
Hi , please note the problem happen with windows 10 also .. if you looked at my screenshot above you will notice it is windows 10 . So if any one knows why it happen i will be very grateful

**Comment by UnluckyY1** [comment]
> Maybe the main cpp file is different?

I am pretty sure that there was no difference also i just made a new clean project example that has only flutter_meedu_videoplayer on pubspec and that will cause the to crash immediately at the start 

[repo link ](https://github.com/UnluckyY1/video_player_crash_example)

**Comment by zezo357** [comment]
> > Maybe the main cpp file is different?
> 
> I am pretty sure that there was no difference also i just made a new clean project example that has only flutter_meedu_videoplayer on pubspec and that will cause the app to crash immediately at the start
> 
> [repo link ](https://github.com/UnluckyY1/video_player_crash_example)
it works in my case
![image](https://user-images.githubusercontent.com/25157308/194620867-87db3d38-135f-4a97-be99-f03525ef886d.png)

**Comment by UnluckyY1** [comment]
@moghoneim-code can you share your flutter doctor, please?

**Comment by moghoneim-code** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19043.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

![image](https://user-images.githubusercontent.com/72418844/194641883-e447a738-0884-4d56-892f-bf5f8bfbd3e0.png)

**Comment by zezo357** [comment]
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19043.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code, 64-bit edition (version 1.71.2)
[√] Connected device (3 available)
    ! Device emulator-5554 is offline.
[√] HTTP Host Availability

**Comment by zezo357** [comment]
Visual Studio Community version?

**Comment by UnluckyY1** [comment]
> Visual Studio Community version?

i really doubt about it but i will do some tests with the version that you are using

**Comment by zezo357** [comment]
> > Visual Studio Community version?
> 
> i really doubt about it but i will do some tests with the version that you are using

Will wait for you since I really can't find the problem

**Comment by ledao** [comment]
I have the same problem both in win10 and win11.
It seems something go wrong in screen brightness plugin. I just comment line 127, 146-153 in screen_brightness_windows_plugin.cpp (screen_brightness_windows_plugin project in runner solution),  the abort disapears. 
it's GetMonitorBrightness function, I do not know why.

**Comment by zezo357** [comment]
> I have the same problem both in win10 and win11.
> It seems something go wrong in screen brightness plugin. I just comment line 127, 146-153 in screen_brightness_windows_plugin.cpp (screen_brightness_windows_plugin project in runner solution),  the abort disapears. 
> it's GetMonitorBrightness function, I do not know why.

Can you post the issue in the screen brightness plugin? To make sure if the original issuer can fix it

**Comment by UnluckyY1** [comment]
still having the same crash even after updating to the last Visual Studio version as expected  :

[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.22000.918], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.72.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

anyway, at least now we know that the issue is caused by screen_brightness and honestly I am not an expert on windows c++ development, i think it would be better to disable the brightness feature until the writer of the plugin makes a fix for it

**Comment by zezo357** [comment]
> still having the same crash even after updating to the last Visual Studio version as expected :
> 
> [√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.22000.918], locale fr-FR) [√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1) [√] Chrome - develop for the web [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5) [√] Android Studio (version 2021.2) [√] VS Code (version 1.72.0) [√] Connected device (3 available) [√] HTTP Host Availability
> 
> anyway, at least now we know that the issue is caused by screen_brightness and honestly I am not an expert on windows c++ development, i think it would be better to disable the brightness feature until the writer of the plugin makes a fix for it

i think this should work in your cas
```
dependency_overrides:
  screen_brightness: "0.2.0"
```

**Comment by UnluckyY1** [comment]
> Reference in new i
0.1.4 
actually it should be 

```
dependency_overrides:
  screen_brightness: "0.1.4"
```

**Comment by aaassseee** [comment]
Hi guys. I am the maintainer of screen_brightness. Is that all of the crash from this issue only happened on start up?
If so, can please try with the fix:
```yaml
dependency_overrides:
  screen_brightness_windows:
    git:
      url: https://github.com/aaassseee/screen_brightness.git
      ref: develop
      path: screen_brightness_windows
```

**Comment by aaassseee** [comment]
Package has been released, please do a pub upgrade. Feel free to reopen or create new issues if you have any problems.

**Comment by zezo357** [comment]
> Package has been released, please do a pub upgrade. Feel free to reopen or create new issues if you have any problems.

Thank you ❤️, hope this fixes the problem for the ones who had it
