### ISSUE TITLE
I can't start it on Arch Linux

### ISSUE THREAD

**Issue by 0Franky** [zezo357/flutter_meedu_videoplayer#91]
Hi @zezo357,
I have a problem launching the sample package.
I uploaded the log file where the errors that come out are reported.
I tried searching on the internet but I can't figure out what the problem could be.

[log.txt](https://github.com/zezo357/flutter_meedu_videoplayer/files/11526145/log.txt)

Can you help me?

**Comment by zezo357** [comment]
Just to be sure, are you running your PR?

Since a crash without logs is 99% ffi related so if it's your PR then that makes sense, 


Let me know if that's the case , and can you test on the master branch in that case?

**Comment by 0Franky** [comment]
i was running the master branch

**Comment by 0Franky** [comment]
I did. just in arch doesn't exist apt, so I'll used arch repo to install MVP package.

https://archlinux.org/packages/extra/x86_64/mpv/

**Comment by zezo357** [comment]
> I did. just in arch doesn't exist apt, so I'll used arch repo to install MVP package.
> 
> https://archlinux.org/packages/extra/x86_64/mpv/

Can you test the media_kit package test?

And if that crashes too open an issue for them , they most probably know what the best fix for it

Since I don't know much in Linux 🥲

**Comment by zezo357** [comment]
Did you find a fix?

**Comment by 0Franky** [comment]
not yet. I've been very busy in these days

**Comment by amaxcz** [comment]
works well for me, manjaro mvp kde wayland + flutter
