### ISSUE TITLE
[Linux] App not responding after on Ubuntu on MEDIA_KIT_SHUTDOWN/dispose

### ISSUE THREAD

**Issue by hungryemon** [zezo357/flutter_meedu_videoplayer#93]
![on_back_crash_on_linux](https://github.com/zezo357/flutter_meedu_videoplayer/assets/59959722/b74248a2-7701-41f3-9bec-1252a18e3122)
Reproduce
- Run example and select any option to play video
- After playing video press back button on appbar.

Then app stops responding.

Environment:
- Flutter 3.7.10
- Operating System: Ubuntu 22.04.2 LTS              
- Kernel: Linux 5.19.0-41-generic
- Architecture: x86-64
- Hardware Vendor: Gigabyte Technology Co., Ltd.
- Hardware Model: H410M H V3

**Comment by zezo357** [comment]
It's an issue from flutter, check this 

https://github.com/alexmercerind/media_kit/issues/167
