### ISSUE TITLE
overflow on ios simulator

### ISSUE THREAD

**Issue by Carseason** [zezo357/flutter_meedu_videoplayer#96]
<img width="348" alt="image" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/25239238/502c2ae2-c7a6-413c-821c-09aaffafbf07">

```
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#037af relayoutBoundary=up10 OVERFLOWING:
  creator: Row ← Column ← Positioned ← SecondaryBottomControls ← Stack ← IgnorePointer ← Stack ←
    Padding ← DecoratedBox ← Container ← AnimatedContainer ← FadeTransition ← ⋯
  parentData: offset=Offset(0.0, 3.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
  size: Size(430.0, 76.0)
  direction: horizontal
  mainAxisAlignment: spaceBetween
  mainAxisSize: max
  crossAxisAlignment: center
  textDirection: ltr
  verticalDirection: down
```

**Comment by Carseason** [comment]
Is it possible to change the icon size of the control bar?

**Comment by Carseason** [comment]
It will appear when the player fills the page, maybe it is the reason for the rounded corners of the screen?

**Comment by zezo357** [comment]
> It will appear when the player fills the page, maybe it is the reason for the rounded corners of the screen?

It's just that's the screen width is not wide enough you can try changing the icons size a bit for a fix

**Comment by Carseason** [comment]
> > It will appear when the player fills the page, maybe it is the reason for the rounded corners of the screen?
> 
> It's just that's the screen width is not wide enough you can try changing the icons size a bit for a fix

Sorry, I'm a flutter noob, how can I change the icon size?

**Comment by zezo357** [comment]
final _meeduPlayerController = MeeduPlayerController( 
       controlsStyle: ControlsStyle.primary, 
       responsive: Responsive( 
         fontSizeRelativeToScreen: 2.5, 
         maxFontSize: 16, 
         iconsSizeRelativeToScreen: 10, 
         maxIconsSize: 100, 
         buttonsSizeRelativeToScreen: 10, 
         maxButtonsSize: 100, 
       ));

This will change the icons in relation to screen size

**Comment by Carseason** [comment]
perfectly solved my problem
